== The Word of the Gospel

It is the sincere desire of my heart that every seeker of truth comes to a real,
heart-changing experience of the gospel of Jesus Christ,
and it is with that purpose in mind,
that I share the following considerations on what the gospel is,
what it does in the submissive heart, and more particularly,
why so few in our day experience it to be what it was to Paul, namely,
the very "`power of God.`"^
footnote:[Romans 1:16]

Now I am aware that just as soon as I mention the word gospel,
nearly everyone in the church assumes that they have
already heard it and are quite familiar with it.
But that is precisely what I would like you to consider:
What do you _really_ know of the gospel?
Because the simple truth is that we know no more of the
gospel than the extent to which it is changing our hearts.
It matters very little how familiar we are with the words of the gospel,
or how many times we have heard or even preached the good news of the gospel.
There is only one way to truly _know_ the gospel, and that is to know the living power,
the effective working of the gospel, putting to death the root and nature of sin in man,
and creating all things new in his heart.

The gospel is not words.
It can be _described_ by words, and _declared_ through words.
But the substance of the gospel is not words.
Multitudes have listened to the words of the gospel, believed the words,
and yet known little or nothing of that power which
crucifies the flesh with its passions and desires,
circumcises the heart, purifies the conscience,
and changes the soul into a temple of God.
These are still strangers to the gospel,
no matter how long they have believed or celebrated the words.

In his first letter to the church, Peter makes the following statement:

[.embedded-content-document.letter]
--

Since you have purified your souls in obeying the truth
through the Spirit in sincere love of the brethren,
love one another fervently with a pure heart, having been born again,
not of corruptible seed but incorruptible,
through the word of God which lives and abides forever, because "`All flesh is grass,
and all the glory of man as the flower of the grass.
The grass withers, and its flower falls away, but the Word of the Lord endures forever.`"
[.underline]#Now this is the Word which, by the gospel, was preached to you.#^
footnote:[1 Peter 1:22-25]

--

There is much here worth noting,
but I will highlight a few important things by way of introducing this subject.

_First,_ we read that those who had "`been born again,
not of corruptible seed but incorruptible,
through the word of God which lives and abides forever,`"
had accordingly purified their souls by obeying the truth,
and were thus enabled to love one another fervently with a pure heart.

_Second:_ We see that that which has caused this birth in them,
and this purification of them, and which has allowed heavenly love to flow unrestricted,
is an incorruptible _Seed_ or _Word._
It is an imperishable thing, a living Word,
which is not like the grass or the flowers of the field that fade away,
but is rather an immortal power that endures forever.

_Third:_ We then read in very plain and direct words,
that the preaching of the gospel was meant to bring
about an encounter with this living Word:
"`This is the Word which, _by the gospel,_ was preached to you.`"
That is to say, it was through the preaching of words,
that an eternal Word of life and power--of which man must be born,
and through which he must be purified unto unfeigned
love--was announced or declared to men.

It is evident from this Scripture (as from many others as well),
that it would be quite possible to hear an announcement of gospel words,
without hearing or experiencing the Word of the gospel; or in Peter`'s language,
without hearing the living Word that is preached "`by the gospel.`"
In fact,
if somebody among the original recipients of this letter from Peter were
to read these statements and know in their hearts that they were _not_ among
those who had been purified by obeying the Word of truth,
and were therefore _not_ able to love one another fervently with a pure heart,
they would then most likely (and wisely!) assume that they were not yet sufficiently
familiar with the eternal Word of life and power that does these things.
They as yet knew little of the gospel.

The message or declaration of the gospel can be described in words, believed as words,
and repeated with words;
but the thing described by these words is an experience of power,
an incorruptible Seed or Word,
that purifies the obedient heart so that it can become a conduit of divine love.
And if we know something of this Seed, Word, or Power,
then we know that much of the gospel.
But if all we know is the bare declaration,
or believe the words without abiding in the living Word,
then we have found only the shell or husk of the gospel,
and have come short of the kernel.
This very thing was declared by Christ to those who had already begun to believe in Him:
"`Then Jesus said to those Jews _who believed Him,_ '`If you abide in My word,
you are My disciples indeed, and you shall know the truth,
and the truth shall make you free.`'`"^
footnote:[John 8:31-32]

It is for this very reason that Paul tells us in 1 Thessalonians 1:5,
"`For our gospel did not come to you in word only, but also in power,
and in the Holy Spirit and in much assurance.`"
And also in chapter 2 verse 13 of the same letter he says,
"`For this reason we also thank God without ceasing,
because when you received the word of God which you heard from us,
you welcomed it not as the word of men, but as it is in truth, the word of God,
which also _effectively works_ in you who believe.`"

It is this "`effective working`" that I want you to consider.
And again,
I ask you to give some thought to the following question with humility and sincerity:
How far can we claim to possess a knowledge of the
gospel if we are yet strangers to its effective working?
In his letter to the Romans, Paul says, "`I am not ashamed of the gospel of Christ,
for it is the power of God.`"^
footnote:[Romans 1:16]
Do you know and experience the gospel to be a power that comes from God?
Be honest with yourself in answering these questions.
Nothing is gained by assuming ourselves to be somewhere other than where we are.
Is your faith in the gospel a faith in the power of God?
Paul said,
"`And my speech and my preaching were not with persuasive words of human wisdom,
but in demonstration of the Spirit and of power,
that your faith should not be in the wisdom of men but in the power of God.`"^
footnote:[1 Corinthians 2:4-5]

Let us then consider what this power is, what it does in man,
and why we so desperately need it.
And let us never be content with mere words and definitions,
but rather follow the words towards the experiential knowledge
of that "`implanted Word which is able to save your souls.`"^
footnote:[James 1:21]
Because the gospel of Jesus Christ is a solution, a powerful cure,
a heavenly medicine for a universal disease, and it must be experienced as such.
But no one takes a medicine that they do not think they need.
So if we are going to really know the medicine, and desire its effects,
we must begin by diagnosing the disease.
