== The Problem

Man was created in the image and likeness of God.
God said,
"`Let Us make man in our own image and likeness,`"
and then He breathed into him _His own_ breath of life.
What was this image and likeness?
Some mistakenly assume that this likeness had something to do with man`'s form or shape,
or with the fact that man walks on two feet and can grow a long white beard.
But this has nothing to do with the matter.
God is a Spirit, and there is no form, shape or beard that bears His image and likeness.

In all of creation, only man is said to have borne the image and likeness of God,
and this is because only man was created to bear the light and Spirit of God,
to live as a branch on God`'s vine, to walk in His love, be a partaker of His nature,
and bear His heavenly fruit.
Man`'s ability to bear the image and likeness of God was owing
to the fact that he was created to be a temple of God`'s Spirit,
a partaker of His life, love, righteousness, truth, and wisdom.
Man bore the image of God because God Himself was at work in him
both to will and to do according to His good pleasure.

The image and likeness of God was no external thing.
Nor did it reside in man`'s intellectual abilities or faculty of reason.
The truth is, intelligence and rational thought have no intrinsic goodness or godliness.
Who has not seen how many of the greatest minds in history have held atheistic opinions,
and lived notoriously unrighteous lives?
Every day millions of humans use their faculty of reason
for no better purpose than the pursuit of power,
praise, and sinful pleasures.
The image of God is not found in the brain.
Prior to his fall,
Adam bore the image and likeness of God because the
Spirit of God was the spirit of his soul.
The life, light, love, righteousness, purity, power,
and wisdom of his Creator were the very nature that governed him;
and all that he thought, desired,
and did were only so many manifestations of the goodness
and glory that were hidden in the invisible God.

In a similar sense,
one could say that a diamond bears the image and likeness of the
beauty and color that are concealed in the rays of the sun.
We know that there is a rainbow of colors hidden in the
light that continually streams forth from the sun.
Color and beauty are there, even when our eyes are unable to see them.
But when the rays of the sun pass through a diamond,
the eye suddenly sees sparkles and colors that were there all along.
The diamond, of course, does not _produce_ any of this light and beauty.
In fact,
if you put the diamond in a dark room for a hundred years it would do nothing at all,
manifest nothing at all, and would be indistinguishable from the darkness.
But when the diamond is filled with the light of the sun,
it becomes a beautiful showcase,
a clear revelation and manifestation of all that is normally invisible to the eye of man.
_In this sense, the diamond can truly be said to bear the image and likeness of the sun._
It receives, holds,
and displays before all seeing eyes the beauties and colors that are hidden in light.

But now, if you spoke to a man who was born blind,
and told him that a diamond bears the image and likeness of the sun,
he would have no frame of reference to understand your meaning.
Having never seen the sun, he could only imagine what it meant to bear its image.
And so, holding a diamond in his hands,
he may tell you that the sun must be hard and cold,
because this is what he finds to be true of the diamond.
And if you tell him he is mistaken, he might then say,
"`Then clearly the sun has sharp edges and hard points that
can easily break rocks or carve images on a piece of wood.`"
But all seeing eyes know that this has nothing to do with the sun`'s image and likeness.

Surely you see my point.
The image and likeness of the sun has nothing to do with what the diamond is _in itself,
without the sun,_
but rather with what the sun manifests of itself in and through the diamond.
In just the same way,
the image and likeness of God has nothing to do with
what man can be _without the life of God_,
that is, with what man is _in the flesh_.
Like a diamond in a dark room,
you will never find God`'s image and likeness in
anything man can be or produce of his own.
The only way that man ever did, or ever will, bear the image and likeness of God is if,
like the diamond, he receives, holds,
and displays the beauties and wonders of life and light that are hidden in Christ.

Now the fall or death of the first man was not a death of the outward, fleshly vessel.
God said,
"`In the day that you eat of the tree of the knowledge
of good and evil you shall surely die.`"^
footnote:[Genesis 2:17]
We know that they did eat the fruit, and therefore they most surely did die as well.
But what was this death that they died?

Let us approach the answer to this question by starting with another question:
what is natural death?
How should we define it?
In a few words,
natural death is when the eternal soul of man ceases
to experience the outward life of this physical realm.
The soul continues on as an immortal creation,
but natural death brings an end of its relationship
with the things of this world--with the light,
life, food, creatures, and pleasures of a physical creation.

What then is spiritual death, or the death that Adam died?
Spiritual death is when the soul of man ceases to
experience the inward life of a heavenly realm.
Again, the soul continues on,
but spiritual death brings an end of the soul`'s relationship with the light, life, food,
creatures, and pleasures of a heavenly creation.
This second kind of death is therefore far more severe than the first.
It is the loss of something far greater than flesh and blood, or outward, temporal things.
It is a loss, a separation, an end of a relationship with the light and life of God.
It is a real death to God`'s nature, a total departure from His goodness,
a complete loss of His image and likeness.

It is not uncommon to hear in the church today that
man still bears the image and likeness of God.
But this is not true, unless a man has regained what he has lost.
Man was indeed _created_ in God`'s image and likeness,
but this image was entirely lost when he died to
the reign or kingdom of God`'s life in his soul.
He did not retain God`'s image and likeness after
the fall simply because he retained the same shape,
or because he walked on two feet, grew white hair, and kept his intellectual faculties.
No. The sad truth is that, having died to the life of God, man began to use his mind,
his body,
and all other natural gifts and abilities to manifest
the image and likeness of another father,
with another nature.

Adam _lost_ the image and likeness of God,
and in Genesis chapter 5 we are told that after "`Adam
had lived one hundred and thirty years,
he begot a son in his own likeness, after his image, and named him Seth.`"
Here was a new image and likeness--something like a hard
and cold diamond without the light of the sun.

Now it deserves to be said that man, even after the fall, retained the same _purpose_.
I mean,
it is true that he is still born into this world _in order to_ bear God`'s image and likeness.
But he does not naturally possess this image as he comes into this world born of a woman.
The image and likeness that he bears in his fallen condition is that of his fallen father;
and this is something that the Scriptures bear witness to
in the clearest and strongest terms that language can convey.
The following are just a few examples:

Genesis 6:5 -- "`Then the LORD saw that the wickedness of man was great in the earth,
and that every intent of the thoughts of his heart was only evil continually.`"

Genesis 8:21 -- "`The imagination of man`'s heart is evil from his youth.`"

Jeremiah 17:9 -- "`The heart is more deceitful than all else, and is desperately sick;
who can understand it?`"

John 8:44 -- "`You are of your father the devil,
and the desires of your father you want to do.`"

Romans 3:10 -- "`As it is written: '`There is none righteous, no, not one;
there is none who understands; there is none who seeks after God.
They have all turned aside; they have together become unprofitable;
there is none who does good, no, not one.`'`"

Ephesians 2:1-3 -- "`And you He made alive, who were dead in trespasses and sins,
in which you once walked according to the course of this world,
according to the prince of the power of the air,
the spirit who now works in the sons of disobedience,
among whom also we all once conducted ourselves in the lusts of our flesh,
fulfilling the desires of the flesh and of the mind,
and were by nature children of wrath, just as the others.`"

Will anyone say that these verses describe the image and likeness of God?
These, and multitudes of similar verses,
clearly represent an enormous change from our original condition,
a great fall and loss by which man has become something entirely different than he was.
From a branch of God`'s goodness, righteousness, purity, love, and life,
man became a selfish, proud,
and covetous creature that quickly filled the earth
with violence and with every form of corruption.
"`So God looked upon the earth, and indeed it was corrupt;
for all flesh had corrupted their way on the earth.`"^
footnote:[Genesis 6:12]
Or in the language of Jeremiah, "`I planted you a noble vine, a seed of highest quality.
How then have you turned before Me into the degenerate plant of an alien vine?`"^
footnote:[Jeremiah 2:21]

Yet though these things are declared to us over and over again in Scripture,
there is no real need of inspired texts, outward proofs,
or prophets sent from God to make man aware of his fallen condition.
The clearest and most undeniable evidence for the fall of
man is found daily within our own hearts and minds.
If we have but the willingness to consider it, and the honesty to admit it,
I am convinced that nobody can deny these two basic realities: _First,_
that every man somehow knows what is good; and _second,_
that every man naturally--and often irrationally--inclines toward evil.
Evil is natural for man, and must be resisted; good is contrary to his nature,
and must be deliberately sought.

Here then is the problem, man`'s universal disease.
This is not an idea or doctrine that must be taught and believed with the mind.
It is a change of nature,
a self-evident condition that shows itself in all that man desires and does.
Something terrible happened to the heart of man.
It died to the light and Spirit of God and become something that it was not before.
And in this condition,
we daily find that the only thing man needs to do to further corrupt himself,
to live a life of regret, and to bring pain upon family and friends,
is simply to follow the inclinations of his thoughts and desires!
In Numbers 15:39,
Israel was commanded not to "`follow after your own heart and your own eyes,
after which you played the harlot.`"^
footnote:[NASB]
Consider also these verses from Jeremiah:

11:7-8 -- "`For I earnestly exhorted your fathers
in the day I brought them up out of the land of Egypt,
until this day, rising early and exhorting, saying,
'`Obey My voice.`' Yet they did not obey or incline their ear,
but everyone followed the dictates of his evil heart.`"

18:11-12 -- "`Return now every one from his evil way,
and make your ways and your doings good.`"
And they said, "`That is hopeless!
So we will walk according to our own plans,
and we will every one obey the dictates of his evil heart.`"

3:17 -- "`At that time Jerusalem shall be called the Throne of the LORD,
and all the nations shall be gathered to it, to the name of the LORD, to Jerusalem.
No more shall they follow the dictates of their evil hearts.`"

6:19 -- "`Hear, O earth!
Behold, I will certainly bring calamity on this people--the fruit of their thoughts.`"

Following his own thoughts makes man increasingly evil.
What does this tell us about ourselves?
It tells us that we have a problem.
It tells us that we have no greater enemy than _self._

The heart of man stands up in pride, looks out into the world,
and uses whatever is in his reach--words, money, deceit,
force--to pull things towards himself.
When he succeeds, self-love grows.
When he fails, self-love turns to anger.
When another has more, self-love becomes envy.
When he is threatened, self-love becomes fear.
Having lost his greatest treasure--the life of God--he is driven
to every form of selfishness by the distressing sense of emptiness
and the anxious discontentment that he cannot help but feel.
And yet, all the while he lives this way,
he knows deep in his heart that something is terribly wrong,
that this is not the condition in which man came into this world.

Every man knows what is good, and yet every man knows that he is naturally evil.
If he did not know that he was evil, he would not pretend to be good.
If he did not recognize that there is a right, and that he himself stands in the wrong,
he would not disguise his true motives and hide his real designs.
But even when a man recognizes the evil of his own actions and desires,
still he puts the best construction on them that words will allow.
Though he chooses to do the very same things that he will not tolerate in others,
still he hopes to be regarded as different from them.
And though he lives a life that is contrary to his own convictions,
being judged by his own conscience,
still he cannot bear the thought of being judged by another.

I ask again, what does all of this mean about ourselves?
It means something has changed.
Man is not the same creature that he was before.
He no longer bears the image and likeness of his benevolent Creator.
He has fallen into a condition that is worse than what he is willing to see,
and there he hides from the light because his deeds are evil.

These strong words do not describe other people;
they describe all people who have not been set free from
this nature by the "`effective working`" of the gospel.
This is why I asked you if you knew the power of the gospel.
The words of the gospel cannot save from this problem or heal this disease.
But the power of the gospel can "`put to death the deeds of the body`"^
footnote:[Romans 8:13]
and bring forth a new creation.
The gospel of Jesus Christ does not just call you a new name; it gives you a new nature.
It does not merely forgive sins; it saves from the power of sin.
The gospel is the power of God that works in man to restore all that was lost,
to create man anew in Christ Jesus, to regenerate, restore,
and renew the nature and image that man lost in the fall.

But there are other gospels that have become popular in our day,
gospels that do not strike at the root of man`'s problem, or heal his mortal wound.
There are gospels that call man a new name without making him a new creation,
that call him a saint though he lives like a sinner.
Some say the glory of the gospel is that God no longer sees sin in man.
Or that though man lives in sin, he is nevertheless accounted righteous.
But Christ said He came to make free from sin, to cleanse the inside of the cup,
to make the tree good so that its fruit would be good.
The Son said we can be perfect as our Father in heaven is perfect;
we can walk in the light, love God with all the heart, soul, mind, and strength,
love our enemies, and "`go and sin no more.`"^
footnote:[John 8:11]
John wrote that the Son of God came to destroy the works of the devil in man,
to give us a seed which cannot sin,^
footnote:[1 John 3:8-9]
and which can purify us even as He is pure.^
footnote:[1 John 3:3]
Paul said we can be transformed "`into the same image from glory to glory,`"^
footnote:[2 Corinthians 3:18]
"`conformed to the image of His Son,`"^
footnote:[Romans 8:29]
"`cleansed from all filthiness of the flesh and spirit,
perfecting holiness in the fear of God.`"^
footnote:[2 Corinthians 7:1]

Such a change requires power, not words.
Not a power to call man something he is not, but a power to restore all that man once was.
"`I am not ashamed of the gospel, because it is the power of God.`"
How well do you know the effective working of this gospel power?
Has the gospel created in you a clean heart?
Has it cleansed your thoughts, bowed your will, and filled you with new desires?
Is it crucifying you to the world, making you dead to sin,
fixing your mind on things above, and causing your heart to grow in love?
If your honest answer is "`yes,`" then praise God!--you
indeed know the gospel of Jesus Christ!
But if your answer is "`no,`" or "`very little,`"
then it may be helpful for you to read on,
in order to better understand why this might be the case.
