== Loving His Appearing

Why are there so many Christians whose lives do not evince the light, life,
and love of Jesus Christ that the New Testament describes on nearly every page?
Why have their hearts not been changed?
Why have so many been believers in Jesus for ten, twenty, or forty years,
and yet complain of ongoing slavery to pride, selfishness, lust, anger, fear,
and worldly desires?
Why have many believed the words of the gospel for
so long but experienced so little of its power?

I believe there is a very specific reason for this.
It is because _they do not receive power in the way that it comes._
Paul says, "`For our gospel did not come to you in word only, but also in power,
and in the Holy Spirit and in much assurance.`"^
footnote:[1 Thessalonians 1:5]
What does this mean?
What is this power?
How does it come, and what does it do?
These are extremely important questions,
and rather than assume that we could never overlook or undervalue
the coming of God`'s power in our own lives,
it would be wise to consider these questions humbly before the Lord.

The way that man begins to experience the power of the gospel
is through an inward experience of spiritual light.
The works of God begin with the light of God.
His work in the outward world began when He said "`Let there
be light,`" and from there He began to divide contrary things,
bring growth and increase, and cause glory to spring up in the outward creation.
The new creation, with all of its inward growth and glory, begins in much the same way.
Power comes first as light.
Paul says:

[.embedded-content-document.letter]
--

_But even if our gospel is veiled, it is veiled to those who are perishing,
whose minds the god of this age has blinded, who do not believe,
lest the [.underline]#light of the gospel# of the glory of Christ, who is the image of God,
should shine on them.
For we do not preach ourselves, but Christ Jesus the Lord,
and ourselves your bondservants for Jesus`' sake.
For it is the God who commanded light to shine out of darkness,
who has [.underline]#shone in our hearts# to give the light of the knowledge
of the glory of God in the face of Jesus Christ_.^
footnote:[2 Corinthians 4:3-6]

--

The Scriptures are full of expressions that describe God or Christ as the light of men,
the light of the world, a light that shines in the heart,
a daystar that rises in the heart, the Lamb who is a light to the city of God, etc.
Of course we know that these verses do not speak of outward, natural light.
And yet, spiritual light has something in common with natural light:
it "`makes manifest.`"^
footnote:[Ephesians 5:13]
It allows spiritual senses to perceive what is spiritually real.
John chapter 1 says:

[.embedded-content-document.letter]
--

_In the beginning was the Word, and the Word was with God, and the Word was God.
He was in the beginning with God.
All things came into being through Him,
and without Him nothing came into being that has come into being. [.underline]#In Him
was life, and the life was the light of men.#
And the light shines in the darkness, and the darkness did not comprehend it_.^
footnote:[John 1:1-4]

--

Christians understand that these verses are talking about Jesus Christ--the eternal,
living Word, that was _with_ God in the beginning, and _was_ God in the beginning.
John tells us that the living Word was the creator of all things,
and that through Him all things came into being.
He then tells us that in the Word was life, and that this life was _the light_ of men.
I recognize that these are familiar verses,
but I ask the reader to stop for a minute and consider anew what is being said here:
John is telling us that the _life_ of the eternal Word is a _light_ that shines in men,
though most men do not comprehend it.
Or, said slightly differently,
that the _light_ that shines in men is the _life_ of the Word
that was with God and was God in the beginning.

In the next verses John mentions the coming of John the Baptist,
and tells us that he was not the light, but was sent to bear witness of the true light.
And then in verse 9, speaking of the Word, he says:

[.embedded-content-document.letter]
--

_He was the true Light, which enlightens [.underline]#every man# that comes into the world.
He was in the world, and the world was made by Him, and the world did not know Him.
He came to His own, and His own received Him not.
But as many as received Him, He gave to them power to become the sons of God._

--

It is very important to feel the weight of these truths.
In the Word that made all things was a life, and that life was the true light of men.
This light shines in some measure, or to some degree,
in every man that comes into the world.
But though the world was made by Him, and though He shines in all,
still the world can easily remain in a state where they do not know Him or receive Him.
But, to as many as do receive His light, He gives them _power_ to _become_ sons of God.

I know that many have seen these verses relating exclusively
to Christ`'s outward coming to the Jews of the first century,
and it is certainly true that the majority of the
Jewish people did not receive Christ`'s outward coming.
But because John is speaking here of the eternal Word as the creator of _all men,_
and as a light that shines in "`_every man_ that comes into the world;`"
and since this light is said to shine with the purpose that "`_all men_
though Him might believe,`" and not only the Jews of the first century,
I think it is safe to conclude that these Scriptures are speaking more broadly.
In other words,
it would seem that John has in view _every_ sort of "`appearing`" or "`coming`" of Christ,
and not only His physical appearance for three and a half years,
in one specific place and time in the world.
This is further confirmed by the fact that John does
not introduce the incarnation until verse 14,
where he says, "`And the Word was made flesh, and dwelt among us.`"

Now, it is extremely important to note that, though this light (which, again,
is the life of the eternal Word) shines in the darkness of man,
yet it is only to those who _receive_ Him that power is given to _become_ sons of God.^
footnote:[Some translations have _authority_ or _right_ instead of _power_ here,
// lint-disable invalid-characters "ἐξουσία"
which are also valid translations of the Greek word _ἐξουσία._. However there
are sixty-nine places in the KJV New Testament where the word is translated power,
and it seems the most fitting translation in this context.]
Right here is the answer to our question,
if we only understand what it means to "`receive Him.`"
This is precisely the reason why so few experience the effective working of gospel power.
It is because only those who receive this light, who love its appearing, who accept,
follow, and obey its shining, will experience power to _become_ sons of God--that is,
receive power to be changed back into His image and likeness.

Have you ever thoughtfully considered the verses in the
New Testament that speak of the "`coming`" of the Lord?
There are several of them that cannot possibly be referring to a physical, future event.
For instance, Paul says: "`Therefore judge nothing before the time, until the Lord comes,
who will both bring to light the hidden things of
darkness and reveal the counsels of the hearts.`"^
footnote:[1 Corinthians 4:5]
Is it reasonable to believe that this Scripture is
forbidding all forms of judgment (in our lives,
doctrines, families, the church, etc.) until there has been a future,
outward coming of Christ?
Would this not contradict Paul`'s own words in the following chapter of the same letter?
1 Corinthians 5:3, "`For I indeed, as absent in body but present in spirit,
have already judged (as though I were present) him who has so done this deed.`"
Or 1 Corinthians 5:13, "`For what have I to do with judging those also who are outside?
Do you not judge those who are inside?`"

In chapter 5 of his epistle,
James compares the "`coming of the Lord`" to precious fruit that
springs out of the earth in those who patiently wait for Him.
(See James 5:7-8) Revelation 3:20 speaks of Christ "`coming
in and dining`" with those who hear His voice and open to Him.
Neither of these Scriptures refer to a future event
or a physical move from one place to another.
But I would specifically like to draw your attention to 2 Timothy 4:8, where Paul says:
"`Finally, there is laid up for me the crown of righteousness, which the Lord,
the righteous Judge, will give to me on that Day,
and not to me only but also to all who have loved His appearing.`"
Some Bible translations read "`all who have loved His _coming_,`"
instead of "`appearing,`" but in either case,
readers often assume that Paul is speaking exclusively of a future event.

To be very clear, I most unequivocally believe the Christ _has_ come in the flesh,
that He lived thirty-three years as a man, was crucified, buried, raised from the dead,
and is now seated at the right hand of God.
I also believe that one day He _will_ manifest himself openly to all the world,
put an end to time and the temporal creation, and judge the living and the dead.
But in 2 Timothy 4:8,
it seems beyond any doubt that this coming or appearing
cannot possibly refer to either a past or a future event.
Consider for a moment: What would it mean for a person to love a _future,
physical_ coming of Christ?
Surely it cannot mean to look continually up in the
sky in hopes of seeing an outward appearing.
But could it mean only to love our ideas about what Christ might do in the future?
How would this a valuable spiritual exercise?
And how would this be the way to attain a crown of righteousness?
Did Paul finish his race, stand before the judgment seat, and say,
"`I am prepared to receive my crown of righteousness
because I loved to imagine You coming outwardly,
even though You never did in my lifetime`"? Can something
like this be what Paul is communicating to Timothy?

However,
what _does_ make sense--a great deal of sense--and what is
understandably of the greatest importance for every Christian,
in every age, is the necessity to love, receive,
and obey the Son of God in the way that He "`comes`" or "`appears`" today!
And how does He come to us today?
He comes to us as light, shining in our darkness; and yet _many_ do not love His appearing.

This is precisely what Jesus is describing in John chapter 3,
in his conversation with Nicodemus.

[.embedded-content-document.letter]
--

_And this is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.
But he who does the truth comes to the light, that his deeds may be clearly seen,
that they have been done in God_.^
footnote:[John 3:19-21]

--

Here we read that light _comes_ into the world, but rather than loving its appearing,
men love darkness rather than light.
And why do they love darkness?
Because their deeds are evil,
and they can feel how the light exposes their works and contradicts their will.
But I ask you: when does this light come?
And how does it come?
Can this verse be restricted to the outward coming
of the Son of God in one part of the world,
for a brief moment in history?
Was it possible for men to see their evil deeds and come to the
light _only_ when Christ walked as a man two thousand years ago?
Or is Christ still a light that appears in darkness and teaches men to do the truth?

I present these things to your consideration because I feel it is of the
greatest importance to understand the following three points:

[.numbered-group]
====

[.numbered]
_First,_ with regard to the coming of the Christ,
that though He indeed _did come_ as the Son of Man and Son
of God in a body that God "`prepared for Him,`"^
footnote:[Hebrews 10:5]
and though He _shall come_ as "`a thief in the night,
in the which the heavens shall pass away with a great noise,
and the elements shall melt with fervent heat,`"^
footnote:[2 Peter 3:10]
yet He also _comes now,_ in varying measures or degrees,
in every man that comes into the world,^
footnote:[John 1:9]
as the "`light of the +++[+++entire]
world,`"^
footnote:[John 8:12]
and not just a light for first century Israel.

[.numbered]
_Second,_ that this coming of Christ`'s light in man makes manifest,
or exposes that which is evil, or contrary to God`'s nature and will.
Ephesians 5:13, "`But all things that are reproved are made manifest by the light:
for whatsoever makes manifest is light.`"

[.numbered]
_And third,_ that man has the ability, or rather the tendency,
to "`not receive,`" to "`hate`" and to "`resist`" this coming of light,
and therefore to not receive its power or experience the purpose for its appearing.

====

So who is it that experiences the "`effective working`" of gospel power?
Only those who love, embrace, and obey His appearing.
That is,
only those who bow their neck and unite their will to all that the light makes manifest.
Those who meekly receive its strokes and practice its truth,
instead of hiding in the darkness of their own opinions and desires.
