== Loving His Appearing

Why are there so many Christians whose lives do not evince the light, life,
and love of Jesus Christ that the New Testament describes on nearly every page?
Why have their hearts not been changed?
Why have so many been believers in Jesus for ten, twenty, or forty years,
and yet complain of ongoing slavery to pride, selfishness, lust, anger, fear,
and worldly desires?
Why have many believed the words of the gospel for
so long but experienced so little of its power?

I believe there is a very specific reason for this.
It is because _they do not receive power in the way that it comes._
Paul says, "`For our gospel did not come to you in word only, but also in power,
and in the Holy Spirit and in much assurance.`"^
footnote:[1 Thessalonians 1:5]
What does this mean?
What is this power?
How does it come, and what does it do?
These are extremely important questions,
and rather than assume that we could never overlook or undervalue
the coming of God`'s power in our own lives,
it would be wise to consider these questions humbly before the Lord.

The way that man begins to experience the power of the gospel
is through an inward experience of spiritual light.
The works of God begin with the light of God.
His work in the outward world began when He said "`Let there
be light,`" and from there He began to divide contrary things,
bring growth and increase, and cause glory to spring up in the outward creation.
The new creation, with all of its inward growth and glory, begins in much the same way.
Power comes first as light.
Paul says:

[.embedded-content-document.letter]
--

But even if our gospel is veiled, it is veiled to those who are perishing,
whose minds the god of this age has blinded, who do not believe,
lest the _light of the gospel_ of the glory of Christ, who is the image of God,
should shine on them.
For we do not preach ourselves, but Christ Jesus the Lord,
and ourselves your bondservants for Jesus`' sake.
For it is the God who commanded light to shine out of darkness,
who has shone in our hearts _to give the light of the knowledge
of the glory of God in the face of Jesus Christ_.^
footnote:[2 Corinthians 4:3-6]

--

The Scriptures are full of expressions that describe God or Christ as the light of men,
the light of the world, a light that shines in the heart,
a daystar that rises in the heart, the Lamb who is a light to the city of God, etc.
Of course we know that these verses do not speak of outward, natural light.
And yet, spiritual light has something in common with natural light:
it "`makes manifest.`"^
footnote:[Ephesians 5:13]
It allows spiritual senses to perceive what is spiritually real.
John chapter 1 says:

[.embedded-content-document.letter]
--

In the beginning was the Word, and the Word was with God, and the Word was God.
He was in the beginning with God.
All things came into being through Him,
and without Him nothing came into being that has come into being.
_In Him was life, and the life was the light of men.
And the light shines in the darkness_, and the darkness did not comprehend it.^
footnote:[John 1:1-4]

--

Christians understand that these verses are talking about Jesus Christ--the eternal,
living Word, that was _with_ God in the beginning, and _was_ God in the beginning.
John tells us that the living Word was the creator of all things,
and that through Him all things came into being.
He then tells us that in the Word was life, and that this life was _the light_ of men.
I recognize that these are familiar verses,
but I ask the reader to stop for a minute and consider anew what is being said here:
John is telling us that the _life_ of the eternal Word is a _light_ that shines in men,
though most men do not comprehend it.
Or, said slightly differently,
that the _light_ that shines in men is the _life_ of the Word
that was with God and was God in the beginning.

In the next verses John mentions the coming of John the Baptist,
and tells us that he was not the light, but was sent to bear witness of the true light.
And then in verse 9, speaking of the Word, he says:

[.embedded-content-document.letter]
--

_He was the true Light, which enlightens _every man_ that comes into the world.
He was in the world, and the world was made by Him, and the world did not know Him.
He came to His own, and His own received Him not.
But as many as received Him, He gave to them power to become the sons of God._

--

It is very important to feel the weight of these truths.
In the Word that made all things was a life, and that life was the true light of men.
This light shines in some measure, or to some degree,
in every man that comes into the world.
But though the world was made by Him, and though He shines in all,
still the world can easily remain in a state where they do not know Him or receive Him.
But, to as many as do receive His light, He gives them _power_ to _become_ sons of God.

I know that many have seen these verses relating exclusively
to Christ`'s outward coming to the Jews of the first century,
and it is certainly true that the majority of the
Jewish people did not receive Christ`'s outward coming.
But because John is speaking here of the eternal Word as the creator of _all men,_
and as a light that shines in "`_every man_ that comes into the world;`"
and since this light is said to shine with the purpose that "`_all men_
though Him might believe,`" and not only the Jews of the first century,
I think it is safe to conclude that these Scriptures are speaking more broadly.
In other words,
it would seem that John has in view _every_ sort of "`appearing`" or "`coming`" of Christ,
and not only His physical appearance for three and a half years,
in one specific place and time in the world.
This is further confirmed by the fact that John does
not introduce the incarnation until verse 14,
where he says, "`And the Word was made flesh, and dwelt among us.`"

Now, it is extremely important to note that, though this light (which, again,
is the life of the eternal Word) shines in the darkness of man,
yet it is only to those who _receive_ Him that power is given to _become_ sons of God.^
footnote:[Some translations have _authority_ or _right_ instead of _power_ here,
// lint-disable invalid-characters "ἐξουσία"
which are also valid translations of the Greek word _ἐξουσία._. However there
are sixty-nine places in the KJV New Testament where the word is translated power,
and it seems the most fitting translation in this context.]
Right here is the answer to our question,
if we only understand what it means to "`receive Him.`"
This is precisely the reason why so few experience the effective working of gospel power.
It is because only those who receive this light, who love its appearing, who accept,
follow, and obey its shining, will experience power to _become_ sons of God--that is,
receive power to be changed back into His image and likeness.

Have you ever thoughtfully considered the verses in the
New Testament that speak of the "`coming`" of the Lord?
There are several of them that cannot possibly be referring to a physical, future event.
For instance, Paul says: "`Therefore judge nothing before the time, until the Lord comes,
who will both bring to light the hidden things of
darkness and reveal the counsels of the hearts.`"^
footnote:[1 Corinthians 4:5]
Is it reasonable to believe that this Scripture is
forbidding all forms of judgment (in our lives,
doctrines, families, the church, etc.) until there has been a future,
outward coming of Christ?
Would this not contradict Paul`'s own words in the following chapter of the same letter?
1 Corinthians 5:3, "`For I indeed, as absent in body but present in spirit,
have already judged (as though I were present) him who has so done this deed.`"
Or 1 Corinthians 5:13, "`For what have I to do with judging those also who are outside?
Do you not judge those who are inside?`"

In chapter 5 of his epistle,
James compares the "`coming of the Lord`" to precious fruit that
springs out of the earth in those who patiently wait for Him.
(See James 5:7-8) Revelation 3:20 speaks of Christ "`coming
in and dining`" with those who hear His voice and open to Him.
Neither of these Scriptures refer to a future event
or a physical move from one place to another.
But I would specifically like to draw your attention to 2 Timothy 4:8, where Paul says:
"`Finally, there is laid up for me the crown of righteousness, which the Lord,
the righteous Judge, will give to me on that Day,
and not to me only but also to all who have loved His appearing.`"
Some Bible translations read "`all who have loved His _coming_,`"
instead of "`appearing,`" but in either case,
readers often assume that Paul is speaking exclusively of a future event.

To be very clear, I most unequivocally believe the Christ _has_ come in the flesh,
that He lived thirty-three years as a man, was crucified, buried, raised from the dead,
and is now seated at the right hand of God.
I also believe that one day He _will_ manifest himself openly to all the world,
put an end to time and the temporal creation, and judge the living and the dead.
But in 2 Timothy 4:8,
it seems beyond any doubt that this coming or appearing
cannot possibly refer to either a past or a future event.
Consider for a moment: What would it mean for a person to love a _future,
physical_ coming of Christ?
Surely it cannot mean to look continually up in the
sky in hopes of seeing an outward appearing.
But could it mean only to love our ideas about what Christ might do in the future?
How would this a valuable spiritual exercise?
And how would this be the way to attain a crown of righteousness?
Did Paul finish his race, stand before the judgment seat, and say,
"`I am prepared to receive my crown of righteousness
because I loved to imagine You coming outwardly,
even though You never did in my lifetime`"? Can something
like this be what Paul is communicating to Timothy?

However,
what _does_ make sense--a great deal of sense--and what is
understandably of the greatest importance for every Christian,
in every age, is the necessity to love, receive,
and obey the Son of God in the way that He "`comes`" or "`appears`" today!
And how does He come to us today?
He comes to us as light, shining in our darkness; and yet _many_ do not love His appearing.

This is precisely what Jesus is describing in John chapter 3,
in his conversation with Nicodemus.

[.embedded-content-document.letter]
--

_And this is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.
But he who does the truth comes to the light, that his deeds may be clearly seen,
that they have been done in God_.^
footnote:[John 3:19-21]

--

Here we read that light _comes_ into the world, but rather than loving its appearing,
men love darkness rather than light.
And why do they love darkness?
Because their deeds are evil,
and they can feel how the light exposes their works and contradicts their will.
But I ask you: when does this light come?
And how does it come?
Can this verse be restricted to the outward coming
of the Son of God in one part of the world,
for a brief moment in history?
Was it possible for men to see their evil deeds and come to the
light _only_ when Christ walked as a man two thousand years ago?
Or is Christ still a light that appears in darkness and teaches men to do the truth?

I present these things to your consideration because I feel it is of the
greatest importance to understand the following three points:

_First,_ with regard to the coming of the Christ,
that though He indeed _did come_ as the Son of Man and Son
of God in a body that God "`prepared for Him,`"^
footnote:[Hebrews 10:5]
and though He _shall come_ as "`a thief in the night,
in the which the heavens shall pass away with a great noise,
and the elements shall melt with fervent heat,`"^
footnote:[2 Peter 3:10]
yet He also _comes now,_ in varying measures or degrees,
in every man that comes into the world,^
footnote:[John 1:9]
as the "`light of the +++[+++entire]
world,`"^
footnote:[John 8:12]
and not just a light for first century Israel.

_Second,_ that this coming of Christ`'s light in man makes manifest,
or exposes that which is evil, or contrary to God`'s nature and will.
Ephesians 5:13, "`But all things that are reproved are made manifest by the light:
for whatsoever makes manifest is light.`"

_And third,_ that man has the ability, or rather the tendency,
to "`not receive,`" to "`hate`" and to "`resist`" this coming of light,
and therefore to not receive its power or experience the purpose for its appearing.

So who is it that experiences the "`effective working`" of gospel power?
Only those who love, embrace, and obey His appearing.
That is,
only those who bow their neck and unite their will to all that the light makes manifest.
Those who meekly receive its strokes and practice its truth,
instead of hiding in the darkness of their own opinions and desires.

The Day of Little Things

There are great misunderstandings about the coming of Christ`'s light,
and great imaginations about both _how_ it comes and _what_ it does.
In fact,
I believe there are just as many misunderstandings about
the inward appearing of Christ`'s light in the heart,
as there were about the outward appearance of Christ in the days of His flesh.

When Christ came outwardly, it was not at all in the way that the Jews expected.
The Jews were waiting for something unmistakable and undeniable,
something that solved their perceived problems,
and aligned with their interpretations of Scripture.
But the long-awaited Messiah came as a baby in a manger,
and worked for years as a carpenter in Nazareth.
He began His ministry declaring that the time had been fulfilled,
and the hour had come for God to set up a kingdom in man--an
inward kingdom where the King would conquer an inward enemy.
He passed through the streets of Israel testifying,
not against outward enemies and social injustices, but against every form of sin, evil,
and impurity that had turned the heart of man (the temple of God) into a den of thieves.
Though He came in the unfathomable love of God to seek and save what was lost,
yet He "`struck the earth with the rod of His mouth,`"^
footnote:[Isaiah 11:4]
calling many hypocrites, sons of the devil, white-washed tombs,
dishes and plates that were dirty on the inside,
trees with bad roots that could not produce good fruit.
He said to his own brothers, "`The world cannot hate you,
but it hates Me because I testify of it that its works are evil.`"^
footnote:[John 7:7]
He taught them that uncleanness came from within,
not from touching food with unwashed hands.
He said they were children of flesh that needed to be born of the Spirit,
a people in need of a righteousness that surpassed that of the scribes and Pharisees.
And all of this was said to men and women who possessed the laws of God
and believed themselves to be His only true worshippers.

_This_ is how Jesus Christ came in the flesh,
and it was not at all what they were expecting.
Many of them loved the miracles that healed their bodies and filled their stomachs,
but they did not like His words, and they were greatly offended at His mission.
"`We are Abraham`'s descendants, and have never been in bondage to anyone.
How can You say, '`You will be made free`'? Jesus answered them, "`Most assuredly,
I say to you, whoever commits sin is a slave of sin.`"^
footnote:[John 8:33-34]
Thus, very far from "`receiving`" His coming,
and from "`loving His appearing,`" they hated it, denied it, and sought ways to kill Him,
even while they continued to read their Bibles, attend their synagogues,
and wait for a Messiah that better fit their expectations.

What would you say if I told you that this very thing continues happening today?
Israel overlooked, rejected,
and then crucified their Savior because they did
not like the way that He appeared to them.
But time has not changed the heart of man.
In his natural condition, he is still the very same blind, prejudiced,
and proud creature that rejects the light that testifies against him.

The coming of Christ`'s light in the heart today
is no different than His coming in Israel.
Of course it is an _inward_ rather than an _outward_ manifestation,
but it is _the exact same Jesus Christ,_ with the exact same nature, power, and mission.
The same Messiah who came outwardly now comes inwardly,
and the fallen and proud nature of man gives Him exactly the same reception.

Now be very careful that you do not rashly excuse yourself from this charge.
Just because you love the historical Jesus of the Bible,
does not mean that you love the light and power of Jesus that appears in your heart.
The Jews of the first century loved Moses and all the prophets.
They quoted the prophet`'s words, adorned their tombs,
and firmly believed that they lived according to their doctrines.
Multitudes in Israel praised, memorized and taught the prophets`' words,
even when their hearts were entirely contrary to the Spirit that spoke through them.
More than this,
the Jews of the first century actually found ways to use the words
of Moses and the prophets to convict and to crucify their Savior--the
very One of whom Moses and the prophets had written!

Christians today think it is incredible that the
Jews of the past could be so blind and hard-hearted.
But, do not be offended if I tell you we do the very same thing with the words of Jesus Christ.
Two thousand years have passed,
and people have become very familiar and comfortable with the red words in the Bible.
But it is easy to love His sayings,
and yet hate His _nature_ when it appears in our heart as light.
It is easy to enjoy stories and songs about Jesus,
to marvel at His wisdom and His miracles, and even to believe all of His words,
but when the _light of His life_ shines in the heart, manifesting selfishness, pride,
vain words and evil desires,
we do not "`love His appearing,`" but rather "`love darkness rather than light.`"
We are certain we would never have been among those who crucified the Lord of glory,
and yet in the unseen city of our heart,
we often "`crucify again to ourselves the Son of God and put Him to open shame.`"^
footnote:[Hebrews 6:6]

Again, please do not assume that this is an impossibility for you.
There have always been believers who have zeal for God and for righteousness,
but who do not _submit_ to the righteousness that comes from God.
Speaking of his countrymen according to the flesh, Paul says:

[.embedded-content-document.letter]
--

_For I bear them witness that they have a zeal for God, but not according to knowledge.
For they being ignorant of God`'s righteousness,
and seeking to establish their own righteousness,
have not submitted to the righteousness of God_.^
footnote:[Romans 10:2-3]

--

I freely confess to you that I was one of these,
even when I worked as a leader in the church.
There is a great difference between loving Christ`'s righteousness outside of us,
and submitting to Christ`'s righteousness within us.
There is a great difference between loving Christ`'s words, and loving Christ`'s light.
When a man reads Christ`'s words in the darkness of the natural mind,
they can mean anything at all.
But when the light of His life appears in the heart,
there is a sight and sense of Truth that needs no interpretation.
I have found in my own life that it is possible to
read and sing and even preach Christ`'s words,
while simultaneously hating His appearance every bit as much as the hard-hearted Pharisees.
And why did I hate it?
I hated it for the same reason that the Pharisees did.
I hated it because it threatened something that I loved.
I felt very little threat upon hearing the words of the gospel,
but the light or Word of the gospel was a threat to the life of _self._

Nobody openly claims to hate the coming or appearing of Christ.
The Pharisees of the first century would never have
confessed to despising the coming of their Messiah,
and Christians today are perhaps even more averse to the idea.
But in order to hate the light of Christ, you need only disagree with, resist,
or ignore what it reveals.
To "`love darkness more than light`" is simply to withhold
acceptance and submission to _whatever_ it makes manifest,
and this is rarely done with words.
It is the heart that denies the light of Christ.
I mean, our choices deny Him, our thoughts, pursuits,
and desires contradict Him all day long even without a word being spoken.
And it is in precisely _this way,_ to varying degrees and in hundreds of little decisions,
that all of us have rejected the light of Christ,
and thus failed to experience a growth in the power of His gospel.

Now when I say Christ appears by His light in the heart,
you must not imagine that I am referring to visions, dreams, or even spoken words.
Christ is the living Word of God,
the perfect communication and manifestation of God`'s nature and essence.
Hebrews states He is the "`brightness of His glory and the express image of His person.`"^
footnote:[Hebrews 1:3]
Christ is the living substance of goodness, selfless love and perfect holiness.
His very nature is humility, righteousness, meekness, kindness, and purity.
And when this nature makes its presence felt in the heart,
it is very rarely with words that a man must perceive or interpret.
The coming or appearing of Christ is an inward seeing of who and what He is,
and in this light comes an uncomfortable perception of who and what we are.

For example, a glimpse of His light brings a sense of true goodness and righteousness,
and along with it comes an unpleasant conviction of our own selfishness
or unrighteousness--perhaps in something we did,
thought, said, or desired.
Something within makes us see that our actions or motivations are contrary to truth,
or inconsistent with God`'s nature.
Perhaps there is a sting in our conscience for acting from pride, vanity, selfishness,
or anger, for using our words to call attention to ourselves,
or our clothes to show off our bodies or wealth.
Or maybe we feel a nagging awareness (though we try to suppress
// lint-disable mid-word-uppercase "YouTube"
it) that we are wasting precious time on YouTube,
Netflix, social media, or reading unprofitable books.
These are what many Christians call "`little things,`" and we generally believe they
have little to do with our spiritual growth and our experience of God`'s power.
We typically pay very little attention to these checks and reproofs,
and often both parents and pastors teach us (in their words and
example) that we should not let ourselves feel guilty or ashamed.
In many ways we are encouraged to follow the current of our societies, our friends,
our culture, what we see on the internet or on TV,
rather than pay attention to the still small voice,
the disquieting feeling that pricks our hearts when
our lives and choices contradict the nature of God.
But the truth is (and all who have ever obeyed the light will testify with me)
that these little convictions and corrections _are the beginnings of God`'s power,
the first appearings of the "`light of life._`"

Will any say that these "`little things`" have nothing to do with your spiritual life,
when it is plain that they have everything to do with your heart?
Is not God the God of the heart?
Is there anything more important to Him than what the heart of man is doing and seeking?
Will you say that little things like clothes, jokes, entertainment,
and phones do not matter to God when they clearly matter so much to you?
And if such things already have so much of your heart, your time, and your tongue,
should you expect that God will begin to speak to you about something else?

And where do you think these feelings of discomfort and reproof come from?
Do they spring from the fallen and perverse nature of flesh?
Is your flesh reproving itself?
Was there something inherently good that remained in man after
he died to the life of God--the man of whom God testified:
"`the imagination of man`'s heart is evil from his youth,`"^
footnote:[Genesis 8:21]
and "`every intent of the thoughts of his heart is only evil continually.`"^
footnote:[Genesis 6:5]
Or will you say these convictions for evil, and drawings to righteousness,
come from the accuser of the brethren, the enemy of man`'s soul?
Is Satan`'s kingdom divided against itself?

Some may say, "`These feelings of reproof or condemnation for sin cannot be from God,
because God loves me!`"
But it is precisely _because_ God loves you that He lets you feel
what is both contrary to His nature and opposed to your own good.
Light brings judgment and conviction for sin not so that you live under condemnation,
but so that you turn from the desires of the flesh, learn to walk in the Spirit,
and thereby _come out_ from under condemnation.

This is precisely what Paul tells us in Romans chapter 8:"`There
is therefore now no condemnation to those who are in Christ Jesus,
who do not walk according to the flesh, but according to the Spirit.`"
There is no condemnation for those who walk according to the Spirit.
But _of course_ there is a sense of condemnation or disapproval when those who
have received a gift of the Spirit continue to walk according to the flesh!
Of course God will allow us to feel His enmity and disagreement
with a nature that is contrary to Him in every way--a nature
that we are told "`sets its desires against the Spirit,`"^
footnote:[Galatians 5:17]
and is "`enmity against God.`"^
footnote:[Romans 8:7]
Feelings of rejection aimed at the believer instead of the sin,
with accusations of being a hopeless case, a failure, or a disappointment,
are often the work of the "`accuser of the brethren.`"^
footnote:[Revelation 12:10]
But consciousness of sin, convictions for evil, with drawings toward righteousness,
are the gifts of a merciful God who wants to live with man in His own pure Spirit.

Some allege that these convictions and reproofs are
the operations of man`'s "`natural conscience.`"
But Paul tells us plainly, "`All things that are reproved are made manifest by the light;
for whatsoever makes manifest is light.`"^
// lint-disable invalid-characters "ἐλέγχω"
footnote:[Ephesians 5:13 The word ἐλέγχω in his verse means to rebuke, reprove,
or convict, as it is translated in the KJV.
Other translations use the word expose, which seems to soften the intended meaning.]
Christ says, "`This is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.`"^
footnote:[John 3:19-21]
Elsewhere He tells us, "`When He +++[+++the Spirit of Truth]
has come, He will convict the world of sin, and of righteousness, and of judgment.`"^
footnote:[John 16:8]
Paul writes to Titus,
"`For the grace of God that brings salvation has appeared to all men, teaching us that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age.`"^
footnote:[Titus 2:11]
The author of Hebrews speaks of a "`living and active Word,`"
that "`judges the thoughts and intentions of the heart.`"^
footnote:[Hebrews 4:12]
Here are several Scriptures (among many others that could
be cited) that plainly testify that it is the light,
Spirit, or grace of Jesus Christ that reproves and convicts in the secret of the heart.
Where are the Scriptures that teach that these convictions
arise from the natural conscience of fallen man?

It is not the conscience itself, _but the Light of Christ that shines in the conscience,_
that causes a person to see and feel what is contrary to his Creator.
The conscience is a real and wonderful gift of God.
But without Christ`'s light shining within it, it is like a lantern without a flame,
or a lamp without a bulb.

In all that has been said, the principal point I am desiring to communicate is this:
it is because we do not turn at these oft-repeated rebukes,
do not love and embrace Christ`'s inward appearing,
do not submit our hearts to His light and take it as our guide and teacher;
it is because we make excuses for evil, and for following our own will;
it is because we justify ourselves against our own felt convictions in so many
"`little`" ways that quench and grieve and resist the Spirit of holiness,
that we experience so little growth in the power of the gospel.

These are _not_ "`little things,`" and our attempts to surrender
them will show us just how big a place they have in our hearts.
There is no such thing as a "`little thing.`"
There are only things from above, and things from below.
There are things that are in, for, and from the Spirit of God,
and there are things that are in, for, and from the flesh.
And when a man clings to that which is below,
when he loves his own life more than the truth,
his own will more than the "`reproofs of instruction that are the way of life,`"^
footnote:[Proverbs 6:23]
he shuts the door on the beginnings of the power of God.
He steps on the mustard seed just as it starts to grow.
It is easy to crush an oak tree when it is only two inches tall.
And it is very often the case, that while we wait for something big and unmistakable,
something impressive and more according to our own expectations,
we "`despise the day of small things,`"^
footnote:[Zechariah 4:10]
and miss the coming of gospel power.

The greatest reason why so many remain strangers to the transforming power
of God is because their hearts do not _humbly_ and _continually_ submit to
the first and lowest appearings of His power--the Light of Jesus Christ.
They do not faithfully turn away from the evil,
nor yield their will to the good that they are already able to see.
And because they are not "`faithful in very little,`"^
footnote:[Luke 19:17]
they do not grow to experience more.
In multitudes of little ways, little choices, words, and actions throughout every day,
they grieve, quench, and resist the buddings of gospel power in their hearts.
They grow familiar with gospel doctrine, yet remain strangers to its power,
because the "`effective working`" of God`'s power begins in the heart with a still,
small voice that says, "`Turn at My reproof,
surely I will pour out My Spirit upon you!`"^
footnote:[Proverbs 1:23]
