== The Day of Little Things

There are great misunderstandings about the coming of Christ`'s light,
and great imaginations about both _how_ it comes and _what_ it does.
In fact,
I believe there are just as many misunderstandings about
the inward appearing of Christ`'s light in the heart,
as there were about the outward appearance of Christ in the days of His flesh.

When Christ came outwardly, it was not at all in the way that the Jews expected.
The Jews were waiting for something unmistakable and undeniable,
something that solved their perceived problems,
and aligned with their interpretations of Scripture.
But the long-awaited Messiah came as a baby in a manger,
and worked for years as a carpenter in Nazareth.
He began His ministry declaring that the time had been fulfilled,
and the hour had come for God to set up a kingdom in man--an
inward kingdom where the King would conquer an inward enemy.
He passed through the streets of Israel testifying,
not against outward enemies and social injustices, but against every form of sin, evil,
and impurity that had turned the heart of man (the temple of God) into a den of thieves.
Though He came in the unfathomable love of God to seek and save what was lost,
yet He "`struck the earth with the rod of His mouth,`"^
footnote:[Isaiah 11:4]
calling many hypocrites, sons of the devil, white-washed tombs,
dishes and plates that were dirty on the inside,
trees with bad roots that could not produce good fruit.
He said to his own brothers, "`The world cannot hate you,
but it hates Me because I testify of it that its works are evil.`"^
footnote:[John 7:7]
He taught them that uncleanness came from within,
not from touching food with unwashed hands.
He said they were children of flesh that needed to be born of the Spirit,
a people in need of a righteousness that surpassed that of the scribes and Pharisees.
And all of this was said to men and women who possessed the laws of God
and believed themselves to be His only true worshippers.

_This_ is how Jesus Christ came in the flesh,
and it was not at all what they were expecting.
Many of them loved the miracles that healed their bodies and filled their stomachs,
but they did not like His words, and they were greatly offended at His mission.
"`We are Abraham`'s descendants, and have never been in bondage to anyone.
How can You say, '`You will be made free`'? Jesus answered them, "`Most assuredly,
I say to you, whoever commits sin is a slave of sin.`"^
footnote:[John 8:33-34]
Thus, very far from "`receiving`" His coming,
and from "`loving His appearing,`" they hated it, denied it, and sought ways to kill Him,
even while they continued to read their Bibles, attend their synagogues,
and wait for a Messiah that better fit their expectations.

What would you say if I told you that this very thing continues happening today?
Israel overlooked, rejected,
and then crucified their Savior because they did
not like the way that He appeared to them.
But time has not changed the heart of man.
In his natural condition, he is still the very same blind, prejudiced,
and proud creature that rejects the light that testifies against him.

The coming of Christ`'s light in the heart today
is no different than His coming in Israel.
Of course it is an _inward_ rather than an _outward_ manifestation,
but it is _the exact same Jesus Christ,_ with the exact same nature, power, and mission.
The same Messiah who came outwardly now comes inwardly,
and the fallen and proud nature of man gives Him exactly the same reception.

Now be very careful that you do not rashly excuse yourself from this charge.
Just because you love the historical Jesus of the Bible,
does not mean that you love the light and power of Jesus that appears in your heart.
The Jews of the first century loved Moses and all the prophets.
They quoted the prophet`'s words, adorned their tombs,
and firmly believed that they lived according to their doctrines.
Multitudes in Israel praised, memorized and taught the prophets`' words,
even when their hearts were entirely contrary to the Spirit that spoke through them.
More than this,
the Jews of the first century actually found ways to use the words
of Moses and the prophets to convict and to crucify their Savior--the
very One of whom Moses and the prophets had written!

Christians today think it is incredible that the
Jews of the past could be so blind and hard-hearted.
But, do not be offended if I tell you we do the very same thing with the words of Jesus Christ.
Two thousand years have passed,
and people have become very familiar and comfortable with the red words in the Bible.
But it is easy to love His sayings,
and yet hate His _nature_ when it appears in our heart as light.
It is easy to enjoy stories and songs about Jesus,
to marvel at His wisdom and His miracles, and even to believe all of His words,
but when the _light of His life_ shines in the heart, manifesting selfishness, pride,
vain words and evil desires,
we do not "`love His appearing,`" but rather "`love darkness rather than light.`"
We are certain we would never have been among those who crucified the Lord of glory,
and yet in the unseen city of our heart,
we often "`crucify again to ourselves the Son of God and put Him to open shame.`"^
footnote:[Hebrews 6:6]

Again, please do not assume that this is an impossibility for you.
There have always been believers who have zeal for God and for righteousness,
but who do not _submit_ to the righteousness that comes from God.
Speaking of his countrymen according to the flesh, Paul says:

[.embedded-content-document.letter]
--

_For I bear them witness that they have a zeal for God, but not according to knowledge.
For they being ignorant of God`'s righteousness,
and seeking to establish their own righteousness,
have not submitted to the righteousness of God_.^
footnote:[Romans 10:2-3]

--

I freely confess to you that I was one of these,
even when I worked as a leader in the church.
There is a great difference between loving Christ`'s righteousness outside of us,
and submitting to Christ`'s righteousness within us.
There is a great difference between loving Christ`'s words, and loving Christ`'s light.
When a man reads Christ`'s words in the darkness of the natural mind,
they can mean anything at all.
But when the light of His life appears in the heart,
there is a sight and sense of Truth that needs no interpretation.
I have found in my own life that it is possible to
read and sing and even preach Christ`'s words,
while simultaneously hating His appearance every bit as much as the hard-hearted Pharisees.
And why did I hate it?
I hated it for the same reason that the Pharisees did.
I hated it because it threatened something that I loved.
I felt very little threat upon hearing the words of the gospel,
but the light or Word of the gospel was a threat to the life of _self._

Nobody openly claims to hate the coming or appearing of Christ.
The Pharisees of the first century would never have
confessed to despising the coming of their Messiah,
and Christians today are perhaps even more averse to the idea.
But in order to hate the light of Christ, you need only disagree with, resist,
or ignore what it reveals.
To "`love darkness more than light`" is simply to withhold
acceptance and submission to _whatever_ it makes manifest,
and this is rarely done with words.
It is the heart that denies the light of Christ.
I mean, our choices deny Him, our thoughts, pursuits,
and desires contradict Him all day long even without a word being spoken.
And it is in precisely _this way,_ to varying degrees and in hundreds of little decisions,
that all of us have rejected the light of Christ,
and thus failed to experience a growth in the power of His gospel.

Now when I say Christ appears by His light in the heart,
you must not imagine that I am referring to visions, dreams, or even spoken words.
Christ is the living Word of God,
the perfect communication and manifestation of God`'s nature and essence.
Hebrews states He is the "`brightness of His glory and the express image of His person.`"^
footnote:[Hebrews 1:3]
Christ is the living substance of goodness, selfless love and perfect holiness.
His very nature is humility, righteousness, meekness, kindness, and purity.
And when this nature makes its presence felt in the heart,
it is very rarely with words that a man must perceive or interpret.
The coming or appearing of Christ is an inward seeing of who and what He is,
and in this light comes an uncomfortable perception of who and what we are.

For example, a glimpse of His light brings a sense of true goodness and righteousness,
and along with it comes an unpleasant conviction of our own selfishness
or unrighteousness--perhaps in something we did,
thought, said, or desired.
Something within makes us see that our actions or motivations are contrary to truth,
or inconsistent with God`'s nature.
Perhaps there is a sting in our conscience for acting from pride, vanity, selfishness,
or anger, for using our words to call attention to ourselves,
or our clothes to show off our bodies or wealth.
Or maybe we feel a nagging awareness (though we try to suppress
// lint-disable mid-word-uppercase "YouTube"
it) that we are wasting precious time on YouTube,
Netflix, social media, or reading unprofitable books.
These are what many Christians call "`little things,`" and we generally believe they
have little to do with our spiritual growth and our experience of God`'s power.
We typically pay very little attention to these checks and reproofs,
and often both parents and pastors teach us (in their words and
example) that we should not let ourselves feel guilty or ashamed.
In many ways we are encouraged to follow the current of our societies, our friends,
our culture, what we see on the internet or on TV,
rather than pay attention to the still small voice,
the disquieting feeling that pricks our hearts when
our lives and choices contradict the nature of God.
But the truth is (and all who have ever obeyed the light will testify with me)
that these little convictions and corrections _are the beginnings of God`'s power,
the first appearings of the "`light of life._`"

Will any say that these "`little things`" have nothing to do with your spiritual life,
when it is plain that they have everything to do with your heart?
Is not God the God of the heart?
Is there anything more important to Him than what the heart of man is doing and seeking?
Will you say that little things like clothes, jokes, entertainment,
and phones do not matter to God when they clearly matter so much to you?
And if such things already have so much of your heart, your time, and your tongue,
should you expect that God will begin to speak to you about something else?

And where do you think these feelings of discomfort and reproof come from?
Do they spring from the fallen and perverse nature of flesh?
Is your flesh reproving itself?
Was there something inherently good that remained in man after
he died to the life of God--the man of whom God testified:
"`the imagination of man`'s heart is evil from his youth,`"^
footnote:[Genesis 8:21]
and "`every intent of the thoughts of his heart is only evil continually.`"^
footnote:[Genesis 6:5]
Or will you say these convictions for evil, and drawings to righteousness,
come from the accuser of the brethren, the enemy of man`'s soul?
Is Satan`'s kingdom divided against itself?

Some may say, "`These feelings of reproof or condemnation for sin cannot be from God,
because God loves me!`"
But it is precisely _because_ God loves you that He lets you feel
what is both contrary to His nature and opposed to your own good.
Light brings judgment and conviction for sin not so that you live under condemnation,
but so that you turn from the desires of the flesh, learn to walk in the Spirit,
and thereby _come out_ from under condemnation.

This is precisely what Paul tells us in Romans chapter 8:"`There
is therefore now no condemnation to those who are in Christ Jesus,
who do not walk according to the flesh, but according to the Spirit.`"
There is no condemnation for those who walk according to the Spirit.
But _of course_ there is a sense of condemnation or disapproval when those who
have received a gift of the Spirit continue to walk according to the flesh!
Of course God will allow us to feel His enmity and disagreement
with a nature that is contrary to Him in every way--a nature
that we are told "`sets its desires against the Spirit,`"^
footnote:[Galatians 5:17]
and is "`enmity against God.`"^
footnote:[Romans 8:7]
Feelings of rejection aimed at the believer instead of the sin,
with accusations of being a hopeless case, a failure, or a disappointment,
are often the work of the "`accuser of the brethren.`"^
footnote:[Revelation 12:10]
But consciousness of sin, convictions for evil, with drawings toward righteousness,
are the gifts of a merciful God who wants to live with man in His own pure Spirit.

Some allege that these convictions and reproofs are
the operations of man`'s "`natural conscience.`"
But Paul tells us plainly, "`All things that are reproved are made manifest by the light;
for whatsoever makes manifest is light.`"^
// lint-disable invalid-characters "ἐλέγχω"
footnote:[Ephesians 5:13 The word ἐλέγχω in his verse means to rebuke, reprove,
or convict, as it is translated in the KJV.
Other translations use the word expose, which seems to soften the intended meaning.]
Christ says, "`This is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.`"^
footnote:[John 3:19-21]
Elsewhere He tells us, "`When He +++[+++the Spirit of Truth]
has come, He will convict the world of sin, and of righteousness, and of judgment.`"^
footnote:[John 16:8]
Paul writes to Titus,
"`For the grace of God that brings salvation has appeared to all men, teaching us that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age.`"^
footnote:[Titus 2:11]
The author of Hebrews speaks of a "`living and active Word,`"
that "`judges the thoughts and intentions of the heart.`"^
footnote:[Hebrews 4:12]
Here are several Scriptures (among many others that could
be cited) that plainly testify that it is the light,
Spirit, or grace of Jesus Christ that reproves and convicts in the secret of the heart.
Where are the Scriptures that teach that these convictions
arise from the natural conscience of fallen man?

It is not the conscience itself, _but the Light of Christ that shines in the conscience,_
that causes a person to see and feel what is contrary to his Creator.
The conscience is a real and wonderful gift of God.
But without Christ`'s light shining within it, it is like a lantern without a flame,
or a lamp without a bulb.

In all that has been said, the principal point I am desiring to communicate is this:
it is because we do not turn at these oft-repeated rebukes,
do not love and embrace Christ`'s inward appearing,
do not submit our hearts to His light and take it as our guide and teacher;
it is because we make excuses for evil, and for following our own will;
it is because we justify ourselves against our own felt convictions in so many
"`little`" ways that quench and grieve and resist the Spirit of holiness,
that we experience so little growth in the power of the gospel.

These are _not_ "`little things,`" and our attempts to surrender
them will show us just how big a place they have in our hearts.
There is no such thing as a "`little thing.`"
There are only things from above, and things from below.
There are things that are in, for, and from the Spirit of God,
and there are things that are in, for, and from the flesh.
And when a man clings to that which is below,
when he loves his own life more than the truth,
his own will more than the "`reproofs of instruction that are the way of life,`"^
footnote:[Proverbs 6:23]
he shuts the door on the beginnings of the power of God.
He steps on the mustard seed just as it starts to grow.
It is easy to crush an oak tree when it is only two inches tall.
And it is very often the case, that while we wait for something big and unmistakable,
something impressive and more according to our own expectations,
we "`despise the day of small things,`"^
footnote:[Zechariah 4:10]
and miss the coming of gospel power.

The greatest reason why so many remain strangers to the transforming power
of God is because their hearts do not _humbly_ and _continually_ submit to
the first and lowest appearings of His power--the Light of Jesus Christ.
They do not faithfully turn away from the evil,
nor yield their will to the good that they are already able to see.
And because they are not "`faithful in very little,`"^
footnote:[Luke 19:17]
they do not grow to experience more.
In multitudes of little ways, little choices, words, and actions throughout every day,
they grieve, quench, and resist the buddings of gospel power in their hearts.
They grow familiar with gospel doctrine, yet remain strangers to its power,
because the "`effective working`" of God`'s power begins in the heart with a still,
small voice that says, "`Turn at My reproof,
surely I will pour out My Spirit upon you!`"^
footnote:[Proverbs 1:23]
