== Introduction

Few words are more familiar to Christians than grace, and yet,
the experience of grace--the manner of its coming, its work in the heart,
and the way to "`continue in it`"^
footnote:[Acts 13:43]--remains a mystery to many.
It is true that there are a variety of conflicting opinions and teachings about grace,
but the real reason for any unfamiliarity with its work
cannot be attributed to any ignorance in the mind,
but rather to an unwillingness in the heart to live and to remain where grace is known.

While men live in their own will, strength, and wisdom, they live outside, or above,
the grace of God.
They are like people who walk on dry land, dying of thirst,
when there is a river of water flowing just below their feet.
Walking in our own will, our own strength, our own light and way,
is the surest way to "`set aside the grace of God,`"^
footnote:[Galatians 2:21]
because in that condition we are too high to find it.
To walk in the flesh is to trample grace under our feet,
often without ever knowing that it is there.

That being the case, the way to find and feel the grace of God--that is,
the way to experience the effective operation of His power--is to _come down_,
and to _stay down_, where it can be felt working.
This is called repentance, though many have given another meaning to this word.
Repentance is changing course, coming down, and staying down,
in a place of continual humility, resignation,
and obedience to even the smallest movings, shinings, and manifestations of God`'s power.
And though this idea may be simple enough,
the annals of human history have shown that very few are willing to _live_ in this way.
There are indeed many who descend to this low place
every once in a while when circumstances are painful,
when sin has ruined outward lives, or when the world can offer no solutions to trials,
sickness, confusion, grief, and fear.
Under these conditions, many will descend for a few minutes, or a few days,
and so put their toe in the river of God`'s grace.
But just as soon as they find strength again in the natural man,
or in an outward plan that distracts from inward distress,
they rise back up above the place where grace is known.
They stand back up in their own will.
They return to their own life, their own goals, desires, pursuits, opinions, and ways,
where the power of God ceases to be an experience, and changes quickly into a memory.
Then they will talk about grace, sing of grace,
and tell a testimony of having felt God`'s power in the day of trial,
when they were humbled and softened by a sight of their weakness.
But though there are many who will praise the God who met them in a low place,
_there are far fewer who will continue to walk with Him there._
Yes;
everything in the natural man recoils at the thought
of continuing in that low and desperate place,
where grace becomes the very breath of daily life,
and not just a lifeline thrown in a storm.

However,
there have indeed been some in every generation who
have learned what it means to live "`under grace`"^
footnote:[Romans 6:14-15]--not as a legal status, or an invisible spiritual position,
but as a continual abiding under the power of God.
Paul was a man who lived under grace.
He said, "`By the grace of God I am what I am,`" and he refused to be more.
And because he would be nothing, then grace could be everything.
Because he stayed low, grace was always on top.
Grace triumphed in Paul, and will triumph in all who remain under its power.

The aim of this little book is to present something of the
reality and necessity of living under the grace of God.
But because God`'s grace is the fulfillment of His law,
I intend to touch upon the subject of the law on my way to grace.
