== What is the Law of God?

To understand the law of God, we should take a step back and begin with another question,
namely, _what is a law?_
The first definition that often comes to mind is simply a rule or a commandment,
but the meaning of law goes deeper than this.
Some laws are indeed just rules, but there are other sorts of laws as well.
In the outward creation there are laws of nature, like the laws of motion, gravity,
or thermodynamics.
There are also civil laws, laws of science, and traffic laws.
In Scripture we read of the written Mosaic Law,
but also of an invisible law of sin and death, a law of righteousness, a law of liberty,
and the law of the Spirit of life in Christ Jesus.
In Romans chapter seven,
Paul speaks of finding two different and contrary
laws working at the same time in his own person.

In looking for a definition of law that works in all cases, I suggest the following:
_A law is governing power.
In other words, it is a rule or authority that never changes,
and that demands conformity or obedience when acting upon something else._
The law of gravity, for example,
is a constant rule or power that never changes and that demands obedience
or conformity whenever it is acting upon an object in this world.
A traffic law is also a constant authority, or a power made by legislation.
It does not change because of man`'s opinions or preferences,
and it demands obedience or conformity when acting upon all drivers.
What about the law of sin?
Sin, too, is a constant power or nature that never changes.
It always seeks self, always works evil and darkness, and when it acts upon man,
it demands obedience and conformity as it continually distorts the image
and likeness of God in all who walk according to the flesh.

Law did not begin with Moses.
Law began with God, and it began as something holy, just, and good.
Before the fall, God`'s _life and nature_ was the law,
or governing power over all created things.
I am not referring to written or spoken rules or commandments.
I mean that the very life of God--who He was, how He was, what He was, knew, felt, saw,
and loved,
His very nature and being manifesting itself--this
was the constant rule or power that never changed,
and that acted upon all of His creation,
bringing all into a living conformity to Himself.
This was not a forced conformity to outward rules,
or a written code of required compliance.
It was an inward and outward conformity and unity, a living power and rule that,
when acting upon all of creation,
brought it into a perfect alignment and conformity with its Creator.

In the beginning,
everything in creation lived happily and harmoniously
in and by this law of God`'s love and goodness.
Every created thing, animate and inanimate,
kept its place and position in the will and power of God.
There was nothing contrary to Him, nothing independent of Him,
not a single thing that opposed His nature, life, or government.
And therefore all of creation abode for a time in a perfect _state of glory._
Glory is simply a visible manifestation of God`'s invisible goodness,
and for a short while both the natural and the spiritual universe were living
environments that happily received and gloriously displayed the wonders,
perfections, and attributes of God.
All things naturally and freely kept this perfect law of liberty.
It was their created state or abode.
All things willingly submitted to His government,
and this happy submission was both the creature`'s joy and the Creator`'s majesty.

Now there were at least two types of beings that were created to receive and
manifest an even greater measure of God`'s glory than the rest of creation,
and these two beings were humans and angels.
Unlike the rest of the natural creation,
humans are specifically said to have been created "`in the image and likeness of God.`"^
footnote:[See Genesis 1:26]
And by the account given of them in Scripture,
we can assume angels to have been created with much the same purpose and potential.
But both of these creatures, in receiving a greater capacity for glory,
had also a greater freedom to turn against the perfect law of God.
That is, they could either submit to and keep their abode in the law of God`'s life,
will, and nature, or they could turn away and break themselves off from it.

This is precisely what happened.
Some of the angels "`did not keep their proper domain,
but left their own abode,`" and so were separated from God`'s glory and "`reserved
in everlasting chains under darkness for the judgment of the great day.`"^
footnote:[Jude 1:6]
These were the first _lawbreakers,_ that is,
the first creatures in all of creation that transgressed
the holy law of God`'s perfect will and power.
They refused to be acted upon by His unchanging nature.
They rejected conformity to His eternal truth.
They broke His spiritual law,
and quickly found in themselves the horrible fruit of their own foolish choice.
From glorious angels, they became miserable demons.
They were cast out of their heavenly home, and now wander "`to and fro in the earth`"^
footnote:[Job 1:7]
in a dark and contrary nature, "`seeking whom they may devour.`"^
footnote:[1 Peter 5:8]

Tragically, it was not long before mankind followed in their footsteps.
Man was the crown of the natural creation,
the clearest image and likeness of the invisible God in the physical universe.
But he too used the gift of his will--a gift that empowered him to seek, cling to, love,
and worship the goodness of his Creator--to turn from God,
and to pursue the lusts of his earthly eyes, the lusts of his flesh,
and the pride of his own life.
In this way he too transgressed the living law of God.
He stepped out of his proper domain,
left his heavenly abode in the will and nature of God, and immediately brought disorder,
deformity, and a curse upon all the creation below.

Suddenly then, there was _a new and different law_ working in the creation of God.
What was this new law?
It was "`the law of sin and death`"^
footnote:[Romans 8:2]
--a new and unchanging rule or power that demanded
obedience and conformity from everything that it acted upon.

Sin can be simply defined as contrariness or enmity with the perfect law or nature of God.
It is the presence and power of something else in God`'s
creation that lives and grows by a contrary will.
God is the creator of the universe, but He is not the creator of sin.
Sin was not created; it was born when perfect creatures, in a perfect creation,
withdrew their will from the law of heavenly life to work in independence, or _self._
This is the origin of sin, and it remains the power of sin to this day.
Whenever a creature uses the gifts of God to turn from God into self,
it departs from the law of life into the law of sin,
where spiritual death becomes the inevitable consequence.
In the language of Paul, "`The wages of sin is death.`"^
footnote:[Romans 6:23]

Sin is very much like a cancer that grows in a healthy human body.
Health is not the creator of cancer; it is not a part of a body`'s design.
But when a stubborn disorder begins to use the life, the cells,
and the energy of a person to cause a growth that is contrary to the good of the body,
then disease is born, and death is often the unavoidable outcome.
Sin is a cancer that appeared in the perfect creation of God when the
will of angels and men turned against God`'s law of life and goodness.
And everything that lives in this independent will, that is,
everything that walks in _self-will_, is under this law of sin, is made a slave to it,
and is led by it down a path that leads to destruction.
This is the law of sin and death.

Though Israel was a subject territory under Roman dominion during the time of Christ,
the Jews considered themselves free because there were few
outward laws restricting their liberty to live,
work, and worship their God.
Jesus, however,
told them that there was a much greater law that had jurisdiction over them,
and that every act of sin was a proof of its dominion.

[.embedded-content-document]
--

They answered Him, "`We are Abraham`'s descendants,
and have never been in bondage to anyone.
How can You say, '`You will be made free`'?`" Jesus answered them, "`Most assuredly,
I say to you, [.underline]#whoever commits sin is a slave of sin#.`"^
footnote:[John 8:33-34]

--

Just as long as this new law of sin and death was the governing principle in men--so
long as it was the never-changing rule that demanded conformity and obedience when acting
upon man`'s heart--there was nothing that could be done for their salvation and happiness.
In other words, if men would live as slaves to sin,
they would necessarily die in their sins,
and could in no way return to their original condition.
"`Then Jesus said to them again, '`I am going away, and you will seek Me,
and will die in your sin.
Where I go you cannot come.`'`"^
footnote:[John 8:21]

Forgiveness alone is not the solution to this problem.
Forgiveness of sin is a wonderful gift, and a necessary part of God`'s work of redemption.
But forgiveness by itself does not kill this cancer, or heal this disease in creation.
The solution that man needed, and the very thing that Jesus Christ offered,
was __a "`new and living way`"^
footnote:[Hebrews 10:20]
to come back into and under God`'s original law of life.__
Man needed to be born again of that life to which he had died.
He needed to be set free from the "`law of sin and death`"
by the "`law of the Spirit of life in Christ Jesus.`"^
footnote:[Romans 8:2]
But before life and immortality were brought to light by the gospel,
a written law of righteous commands was given to God`'s people,
being "`added because of transgression.`"^
footnote:[Galatians 3:19]
