== A Law Written on Tablets

In Galatians 3:19, Paul writes, "`What purpose then does the law serve?
It was added because of transgressions,
till the Seed should come to whom the promise was made.`"
What is the law that Paul refers to here?
And what does it mean that it was added because of transgression?
This is evidently not an inward and spiritual law of life,
nor a rule in the physical creation like the law of gravity.
Here, the law Paul had in view was the law of Moses, an outward,
written rule that required conformity or obedience from
the people who were brought into a covenant with God.

In one sense you could say that the written Mosaic Law was like a traffic or civil law,
in that its requirements were placed upon men _from without,_ and not from within.
And it was "`added because of transgressions`" because
mankind had ceased to live by the law of God`'s life^
footnote:[Also called the "`law of faith,`" or the "`law of Christ`" in the New Testament.
See Romans 3:27-8:2, Galatians 6:1-2 Corinthians 9:21]
or nature.
That is to say, because man had departed from God`'s righteousness within,
because he did not submit inwardly to the righteousness that came from God,^
footnote:[See Romans 10:2]
God then added, or superimposed,
a written law of requirements to govern him from without,
until the birth and growth of God`'s Seed in man restored the nature he had lost.

Abel, Noah, and Abraham were men who walked by faith, and at least to some degree,
received and partook of the righteousness of their Creator.
Long before there was an outward law written on stones and parchments,
Abel "`obtained the testimony that he was righteous,`"^
footnote:[Hebrews 11:4 NASB]
"`Noah found grace in the eyes of the Lord,`"^
footnote:[Genesis 6:8]
and "`Abraham believed God, and it was accounted to him for righteousness.`"^
footnote:[Romans 4:3]

But when God called Israel out from their slavery in Egypt,
He found that they were a rebellious and stiff-necked
people that continually murmured against His leadings,
and "`always went astray in their heart.`"^
footnote:[Hebrews 3:10]
Because of continual inward rebellion and outward transgressions,
He placed them under a written law which He delivered to Moses on Mount Sinai.
This was no arbitrary system of rules and regulations to test their obedience,
or to satisfy God`'s righteous standard through rituals and ceremonies.
Very much to the contrary, the Mosaic law was an outward description,
a physical representation or mirror,
of the living law of righteousness that Adam and Eve had forsaken and lost in the beginning.
As the Scriptures amply testify, the written law had the "`form of knowledge and truth,`"^
footnote:[Romans 2:20]
and "`a shadow of the good things to come,`" but "`not the very image of the things.`"^
footnote:[Hebrews 10:1]
That is to say,
the law was the outward form and description of an inward nature
and image that man could not produce on his own.

It is of great importance that we understand that this written law of righteousness
was not at all _contrary_ to the law of life that once reigned in the soul of man.
I emphasize this point because it is common to hear
Christians speak of the law in a disparaging way,
or to represent it as an enemy to the gospel.
But the written law given through Moses should in no way be considered bad or wrong.
Very much to the contrary, Paul tells us it was "`holy, just, and good.`"^
footnote:[Romans 7:12]
The only problem with the law was that it was an
outward description and requirement of righteousness,
and not an inward nature or life of righteousness.
And this indeed created difficulties for the fallen sons of Adam.

In other words,
the reason why Scripture sometimes speaks of the Mosaic Law in an unfavorable way,
is because there was indeed something unfavorable about _man`'s relationship with the law._
The problem was not the law itself, but the fact that an outward,
written law of commandments could not change or overpower
the inward law of sin and death that reigned in fallen man.
It was only words written on a stone, and not a nature written on the heart.
It was a description and a requirement of righteousness, and not a life of righteousness.
And because it was only words that described a nature that man had lost,
the most that it could do was to manifest and reprove
(in a multitude of different ways) the evil,
impurity,
and enmity that man had brought into himself by making
himself a slave to the law of sin and death.

Again, there was absolutely nothing inherently bad or wrong with the written law of God.
Scripture indeed speaks of our becoming free from the "`curse of the law,`"^
footnote:[Galatians 3:13]
the "`yoke`"^
footnote:[Acts 15:10]
of the law, and the "`condemnation`"^
footnote:[2 Corinthians 3:9]
of the law,
but these expressions are not used because the law _itself_ was defective or harmful.
Rather, they are used because _flesh_ is defective and _sin_ is harmful,
and because the written law could do nothing more than expose
and condemn the root of sin and its fruits in man.

Paul corrects this very misunderstanding in several places in his letters.
For instance:

[.embedded-content-document]
--

[.offset]
_Romans 7:7 What shall we say then?
Is the law sin?
Certainly not!
On the contrary, I would not have known sin except through the law._

[.offset]
_Galatians 3:21 Is the law then against the promises of God?
Certainly not!_

[.offset]
_Romans 7:12 Therefore the law is holy, and the commandment holy and just and good.
Has then what is good become death to me?
Certainly not!
But sin, that it might appear sin, was producing death in me through what is good,
so that sin through the commandment might become exceedingly sinful._

--

The written law was not flawed; it was only weak, and for this reason:
because it could not put a stop to the law of sin and death in man.
In Romans 8:3, Paul says the law was "`weak through the flesh.`"
That is to say, on the one hand,
that flesh could not perform the righteousness described by the law; and on the other,
that a written law could not alter the nature of flesh.
In Hebrews we read that the outward commandment was
"`annulled because of its weakness and unprofitableness,
for the law made nothing perfect.`"^
footnote:[Hebrews 7:18-19]
The author does not say the law was unhelpful or useless,
but only weak and unprofitable because it could make nothing perfect.
That is to say, the written law could not remedy man`'s problem.
It was too weak to stop the inertia of a stronger
law that was already at work within him.

Imagine that there was an enormous tree in my yard that
began to sway dangerously in a violent storm of wind,
as though it might fall on my house.
Seeing the danger, I rush inside my house, call the president of the United States,
and ask him to pass a new law declaring:
"`It is henceforth forbidden for any tree to fall on the house of Jason Henderson.`"
The President agrees with my proposal, endorses the law,
secures the approval of Congress, and promptly emails me an official copy.
After printing it out, I run back outside to the tottering tree, read the law aloud,
and think to myself, "`Phew, that was a close call!`"
But within just a few minutes, the wind picks up again,
and the tree--unmoved by my good and just law--splits with a loud crack, falls violently,
and crushes my house.

This is a silly analogy, but no doubt you can see the point:
_the law of gravity is stronger than a written law forbidding gravity to work._
My law was good and fair, but it was "`weak`" because of gravity,
and "`unprofitable`" because it could not save my house.

The written law was only an outward shadow of the law of
life--the inward rule that God wanted to restore to man.
It was a good _description_ of righteousness, but it was not the _life_ of righteousness.
It manifested evil things, and pointed to better things,
but in and of itself it had no power to _impart_ what it described.
And this is precisely what Paul tells us in his letter to the Galatians.

[.embedded-content-document]
--

__Is the Law then contrary to the promises of God?
May it never be!
For if a law had been given which was able to impart life,
then righteousness would indeed have been based on law.__^
footnote:[Galatians 3:21 NASB]

--

Righteousness would have been attained by the written
law if it had been able to impart the life of God.
But that not being the case, man needed something stronger.

Therefore,
seeing that man had lost the inward "`law of life,`" and come under the
"`law of sin and death,`" the God of wisdom and mercy--with an eye towards
man`'s redemption--gave Israel a written law of commandments and ordinances,
setting it over His people as a light and a standard of righteousness.
This was done for at least the following three reasons:

[.numbered-group]
====

[.numbered]
_First,_
so that the description and requirement of righteousness in the written law would uncover,
manifest, and condemn the law of sin that worked in the heart of man.
This is clearly stated in a multitude of Scriptures.^
footnote:[See Romans 3:20-4:15, 5:13, 5:20, 7:5, 7:7-11, 7:13; 2 Corinthians 3:7-9;
Galatians 3:19-3:22]

[.numbered]
_Second,_ that by creating rules and standards of righteousness,
ordinances and ceremonies of worship, precepts of clean and unclean, flesh and Spirit,
etc.,
God would keep the bearers of His testimony from sinking even further into the
degradation and corruption that had overspread the surrounding nations.^
footnote:[See Exodus 19:5-6, Leviticus 18:3-5, 24-30, Deuteronomy 19:9-14]

[.numbered]
_And third_, that by both of these first two things--that is,
both the manifestation of the nature of sin, and the various rules, ordinances,
ceremonies,
types and shadows of the law--God could point the heart of man to the Seed of life,
to the birth of Christ`'s heavenly nature,
that alone could bring man back under the law of life that was lost in the fall.

====

Now, when I speak of the outward law pointing the heart of man to Christ the Seed,
I refer not only to His outward coming as a Man in Israel.
There are indeed many figures and types in the Mosaic law that illustrate
Christ`'s work in the body as the Son of Man and the Lamb of God.
But the far greater share of commandments, ceremonies,
and shadows in the law are illustrative of man`'s need of a present, inward Savior,
one who would slay the bestial nature within, clean the inside of the vessel,
heal the leprosy of the heart,
and make a people inwardly fit to worship the Lord in the beauty of holiness.
