== What is Grace?

Before taking up the subject of grace,
it may be helpful to quickly review some of the most important
things that we have already said about law.
First, we defined law as a constant rule or power that never changes,
and that demands obedience or conformity whenever it acts upon something else.
This is true of all kinds of laws, whether they are outward written laws,
natural laws (like gravity), or spiritual laws, like the law of sin and death,
or the law of the Spirit of life in Christ Jesus.

We saw that, in the beginning, there was no need for any outward or written laws,
because the life, power, nature,
and will of God was operating as a law in and over all creation.
As long as creation continued in its proper domain, in submission to its Creator,
all was goodness, righteousness, and joy.
It was only when man stepped out of this happy submission
to God`'s government (called the kingdom of God),
and transgressed His nature and power and righteousness, that an outward law was added.
It was added because of transgressions until the Seed would
come--whose coming was both outward and inward.

We saw that the problem with this outward law, which was given to man in words,
commandments, and requirements, was that it could not give what it described.
It described righteousness, love, and union with God,
but it could not impart these things, and so it was weak and unable to "`make perfect`"^
footnote:[Hebrews 7:19-9:9, 10:1, 11:40]
those who lived by it or under it.
However, what the law _could do,_ and what it _had to do_ by its very nature,
was point out every way that the natural man fell short of the purity, perfection,
and righteous requirement of his Creator.
In itself, the law was "`holy,
just and good,`" but it worked as a "`ministry of
condemnation`" to the transgressing nature,
exposing and condemning everything in man that was contrary to the life and will of God.

Finally,
we saw that this unfortunate relationship between
the law of God and the sinful nature of fallen man,
was compared by Paul to a permanent marriage relationship
that can only be ended by death.
The law cannot die,
because it describes and requires the unchangeable righteousness of God.
But the sinful nature of flesh, or "`the old man,`"^
footnote:[Ephesians 4:22; Colossians 3:9; Romans 6:6]
can be experientially baptized into the death of Christ,
and the soul joined to the One who was raised from the dead,
in order to bear fruit in righteousness.
In this way, the righteous law is never abolished, changed, forgotten, or repealed.
It is rather _fulfilled_ by the righteousness of Christ living
and reigning in those who walk by His Spirit.

Having understood these things concerning the law,
we are in just the right place to understand the gift of God`'s grace,
_because grace is the coming of what the law could not do._
Grace is powerful where the law was weak, and unlike outward rules and regulations,
grace is indeed able to perfect those who draw near to God.

It is of the greatest importance that every Christian rightly
understands and experiences this incredible gift.
I say _rightly_,
because I believe the enemy of man`'s happiness has sought
to disseminate many falsehoods regarding the grace of God,
several of which had already become popular in the days of the first apostles.

What is grace?
Most Christians associate the word grace with a free gift from God.
When I was young,
I remember hearing an older Christian define the
words grace and mercy in the following way:
"`Grace,`" he said, "`is when you get something you _do not_ deserve;
mercy is when you do not get something that you _do_ deserve.`"
I remember at the time being somewhat struck with the profundity of this statement,
but I realized later that it actually told me very little about grace.
Understanding that we do not deserve grace, does not tell us anything about what it is.
Christians sometimes exclaim: "`Grace is the free gift of God!`"
Indeed it is.
But a free gift _of what?_
Much depends upon our understanding of what it is, what it does,
and how we come to experience it.

It is not uncommon today to speak of grace as though it
had something to do with the removal of a law for righteousness.
People often make comments like:
"`Under the law there were strict boundaries and fixed expectations regarding righteousness,
but now Christ`'s death and resurrection have happily
taken all of that away and given us grace.`"
In the mind of many,
the "`grace`" spoken of here is more or less synonymous with _tolerance,_
and for this reason,
the law is frequently contrasted with grace in the sense that one is strict,
and the other is more lenient.
It is thought that law is intolerant,
but grace is much more willing to wink at failures and wrongdoing.
In fact, it has become a popular form of encouragement to say to another,
"`Give yourself some grace!`", meaning, "`Don`'t be so hard on yourself;
everyone makes mistakes.`"

Others make use of Paul`'s expression, being "`under grace`"^
footnote:[Romans 6:14]
as though it referred to a new status or legal position with God,
where all sin is removed from His sight (some say "`past, present and future`"),
or at least where God is less concerned with sin than He was in the days of Moses.
In the mind of these,
the grace of Jesus Christ works somewhat like a giant umbrella that shields
the believer from God`'s searching eyes and unyielding demands.
In fact, it is increasingly common to hear Christians say, "`Thanks to grace,
when God looks at you, He doesn`'t see you at all; He only sees Jesus.`"

But despite the popularity of these ideas,
they really have _nothing_ to do with what the Scriptures affirm about the grace of God.
I mean this quite literally; they have not a single Scripture in their favor.
We have already demonstrated that the righteous law
of God is not to be shielded or softened,
but rather _fulfilled_ by the very nature that it describes.
Jesus`' words are clear:
"`Not one jot or one tittle will by any means pass from the law till all is fulfilled.`"
And Paul insists that,
"`the righteous requirement of the law`" is to be "`_fulfilled_ in us who
do not walk according to the flesh but according to the Spirit.`"

How then should we understand the grace of God?
If you look up every occurrence of the word grace in the New Testament
(something I encourage every Christian to do;
there are about 130 of them),
I believe you cannot help but see that the word grace has
to do with _the power of God freely offered to man,
and effectively working in man._
To offer a very general definition,
the Bible teaches that _grace is the effective working of God`'s power._
And in the majority of these 130 verses,
we see that God`'s grace _comes_ in a very particular way,
and _does_ a very specific thing in the heart of man.
Grace is not a new status.
It is not a legal position.
It has nothing to do with God removing His righteous requirement, with tolerating sin,
or with being unable to see it.
All of this is pure invention.
Grace is the living and effective power of God that works in and upon man.

When speaking of the Child Jesus, Luke writes,
"`And the Child grew and became strong in spirit, filled with wisdom;
and the grace of God was upon Him.`"^
footnote:[Luke 2:40]
Could this possibly mean that a new legal position was upon Jesus?
Or that God was overlooking Jesus`' sins by grace?
Of course not.
Instead, we understand that the living power of God, the effective working of His might,
was in and upon the incarnate Son of God, even when He was a Child.
In Acts 4:33 we read,
"`And with great power the apostles gave witness to the resurrection of the Lord Jesus.
And great grace was upon them all.`"
Clearly the meaning here is that the power of God was manifestly present with them all.
Grace was God`'s power working in their weakness,^
footnote:[See also 2 Corinthians 12:9]
demonstrating what He would do in His own will and by His own strength.

=== A Measure of His Fullness

[.offset]
Consider the following Scripture:

[.embedded-content-document]
--

__And the Word became flesh and dwelt among us, and we beheld His glory,
the glory as of the only begotten of the Father, [.underline]#full of grace and truth.#
John bore witness of Him and cried out, saying, "`This was He of whom I said,
'`He who comes after me is preferred before me,
for He was before me.`'`" [.underline]#And of His fullness we have all received,
and grace for grace.
For the law was given through Moses,
but grace and truth came through Jesus Christ.#__^
footnote:[John 1:14-17]

--

Here John tells us that "`the law was given through Moses.`"
Once again, what was this law that came through Moses?
It was the description and requirement of righteousness
that was given to men because of transgression.
And though it was holy, just, and good in itself,
it was nevertheless weak and unprofitable because
it could not impart the nature that it described;
it could make nothing perfect.
Then John says, "`but grace and truth came through Jesus Christ.`"
What is this grace that comes through Jesus Christ?
Grace is not a description of righteousness in words,
and it most certainly is not the removal or lessening of God`'s righteous requirement.
_Grace is the power of righteousness, the life of righteousness,
the substance and Person of righteousness, given to live, to grow,
and to reign in the soul of man._

Remember Paul`'s words to the Galatians:
"`If there had been a law which could have _imparted_ life,
then righteousness would have been by the law.`"^
footnote:[Galatians 3:21]
We have seen that the written law could not give life,
and for that reason it was called weak and unprofitable.
Grace, however, _can_ give life.
Grace does give life.
In fact, that is precisely what grace is!
It is a gift or measure of the life and power of the One who is righteousness.
Grace is a measure of His fullness.

We also read that the law "`was added because of transgressions,
until the Seed should come to whom the promise was made.`"^
footnote:[Galatians 3:19]
The law exposed transgression, and pointed to the life, nature,
and righteousness of Christ.
It showed the need for Christ, and was "`a tutor to bring us to Christ.`"^
footnote:[Galatians 3:24]
But the actual coming, giving, or sowing of this life-giving Seed is called grace.
Christ the Seed came outwardly, and He also comes inwardly.
Or perhaps it is more accurate to say:
Christ the Seed came outwardly _so that_ He could come inwardly.
The outward work of Christ opened a new and living way in which
every soul could experience the inward work of Christ.

Therefore,
the _first_ and most important thing that we must understand about grace is that
it is the power of God--the effective working of His life and light,
which both came to the world as a Man,
and then was given to all men as an indwelling gift
that can do what the written law could not.
It is a gift of God`'s power, a measure of His life, light, and Spirit,
which comes from the One who is "`full of grace and truth.`"^
footnote:[John 1:14]
"`Of His fullness we have all received, and grace for grace.`"^
footnote:[John 1:16]

=== How Grace Comes

A _second_ essential thing that we need to understand
about grace is _the manner of its coming_,
or the way that we receive and experience it.
This too has been a point of confusion for many.

We have already seen that the grace of God can have distinct manifestations or expressions.
In Acts we observed that the word grace is once used to describe
a visible working of God`'s power in signs and miracles.
In Luke it is used to refer to the power of God secretly
working in Jesus when He was a child.
However, with respect to _its redemptive work in man_,
in both the parables of Jesus and in the letters of the apostles, the gift of grace,
or the effective working of God`'s power,
is most often described as having the nature and property of a heavenly _seed_.
Though in essence it is a measure of the very life and power of God,
yet it begins in the heart as something very small,
and there produces its own increase and kingdom.

There are a variety of terms and metaphors used throughout
Scripture to illustrate the work of grace in man.
This is not because grace is complicated or difficult to understand,
but simply because its work is great,
and because no single name or figure can capture all that it is or does.
It is frequently compared to a seed because it is alive,
because it grows by its own power and will,
and because it produces an increase of its kind.
It is also like a seed in that it must be received into good soil,
and protected from the weeds, thorns, rocks, and birds that are a threat to its growth.
In many places in the New Testament,
the experience of God`'s power or grace is compared
to a living Word (or an "`implanted Word,`"^
footnote:[James 1:21]
a "`Word of faith,`"^
footnote:[Romans 10:8]
the "`Word of His grace,`"^
footnote:[Acts 14:20-3:32]
"`Word of life,`"^
footnote:[Philippians 2:16]
"`living and powerful Word`"^
footnote:[Hebrews 4:12]
etc.) because it is an inward communicator of God`'s will and truth.
It speaks in the heart, separating the precious from the vile,
and yet it can only be heard by circumcised ears.
Elsewhere it is likened to a talent or a mina because the recipient
of grace must cherish and steward it as the greatest of treasures.
If we allow it to increase, and do not bury it in our "`earth,`"^
footnote:[Matthew 25:25 KJV]
it multiplies of its own accord and brings joy to our Master.
It is compared to hidden manna, or bread from heaven,
because it must be carefully gathered and then eaten
every day as the soul`'s inward and heavenly nourishment.
There are also Scriptures where Christ compares the work of grace to a pinch of leaven,
because it spreads, fills, and changes all that man is, all "`three measures of meal;`"^
footnote:[Matthew 13:33]
or to a costly pearl and a hidden treasure, not only for its great value,
but also because it is difficult to find, and impossible to possess,
unless a man is willing to "`forsake all that he has`"^
footnote:[Luke 14:33]
in this world.

All of these terms or figures (with many others) speak of the same
gift of grace that is offered to man in his fallen condition.
And all of them represent it as a living and powerful gift that begins very small,
increases in the right conditions,
and transforms the willing soul into the kingdom of God.
The same idea is communicated throughout the letters
of the apostles in a variety of different expressions.
We read of a "`power that works in us exceedingly
abundantly above all that we ask or think,`"^
footnote:[Ephesians 3:20]
or the "`word of His grace, which is able to build you up and give you an inheritance.`"^
footnote:[Acts 20:32]
Paul prays that all believers might experience "`the
exceeding greatness of His power toward us who believe,
according to the working of His mighty power which
He worked in Christ when He raised Him from the dead.`"^
footnote:[Ephesians 1:19]
We are encouraged to "`grow in the grace and knowledge
of our Lord and Savior Jesus Christ;`"^
footnote:[2 Peter 3:18]
to "`desire the pure milk of the Word, that you may grow thereby,`"^
footnote:[1 Peter 2:2]
and to "`grow up in all things into Him who is the head--even Christ.`"^
footnote:[Ephesians 4:15]

Grace, therefore, is the living and effectual operation of God in the soul,
working and spreading as divine leaven in the inward man.
It is a gift of God`'s own light, life, Word, or Spirit,
given to accomplish the great work of regeneration.
Every other manifestation of God`'s power, every sort of outward miracle, bodily healing,
physical provision, or anything else that God`'s power can do for man,
comes short of resolving his true problem if it does not produce in him the birth,
growth, and dominion of Christ`'s life and nature.
And the reason for this is plain:
It is because the calamitous fall of man was _not_ a loss of outward things.
It was not just the loss of bodily health, outward comforts, supernatural abilities,
or walks with God in a beautiful garden.
The fall of man was the loss of the life, light, and Spirit of God.
It was a death to all goodness, and the end of the soul`'s union with the divine nature.
It therefore cannot be otherwise:
man`'s restoration and redemption can be nothing less than
an experiential recovery of all that was lost.

_This_ is what grace must do for man.
And _this_ is why the effective working of God`'s power is given to him.
Why would fallen man need a grace that winks at selfishness, pride,
and the love of this world?
Or that offers a way to continue in sin without fear of punishment?
How could that help us?
Why would we rejoice in a grace that removes the righteous requirements of the law,
hides our true condition from God`'s sight, and yet leaves us in bondage to sin,
selfishness, and evil desires?
No; what man needs is heavenly power to _see_ his lost condition,
to _turn_ from sin and self to the power of God, to be _born_ of the Spirit,
and to _grow_ into the image and likeness of Christ.

Behold, then, the magnificent gospel of God`'s grace!
What is this gospel of grace?
It is the truth, the reality, _the miracle,_ that God has provided such a power,
a living seed or gift of His own light, life, and Spirit,
that can change man`'s condition, and change man`'s eternity, by changing his nature.
It is a gift of power that--when not grieved or resisted--will effectively
raise and enthrone the life of God in the heart of man.
And if we look anywhere else besides _this_ grace,
we look in vain for a solution to our problem.
That is, if we look anywhere besides _this_ implanted power, _this_ heavenly Seed,
_this_ free gift of life and light that is poured out
on all flesh because of the victorious work of Christ,
then we look to something that cannot help us.

And it is because man stands in total dependency on such a power from
above that Paul was amazed and alarmed that the Galatians were "`turning
away from Him who called them _in the grace of Christ_ to a different gospel.`"^
footnote:[Galatians 1:6]
It was because he knew there was no hope apart from
this heart-transforming power that he repeats twice:
"`Even if we, or an angel from heaven,
preach any other gospel to you than what we have preached to you, let him be accursed.`"^
footnote:[Galatians 1:8]
These are familiar and oft-quoted verses,
but they lose their meaning and force if we change Paul`'s definition of grace.
I say this because there are those who will insist with Paul upon the necessity of grace,
who will sing that grace is amazing, and confess that all depends upon it,
but then will teach that the greatness of grace is that God has removed the law,
that He cares very little about sin,
or that He saves us from the consequences of sin without freeing us from its power.
It therefore must be said that such teachers of grace
have not themselves been taught by grace;
for they clearly show themselves to be unfamiliar with its power,
and strangers to its instruction.

This brings us to a _third_ thing that we should understand about the grace of God:
_Grace is a teacher._
Grace does not sit on a shelf in heaven like a lifeless legal contract.
It is not an inanimate doctrine, or a stationary position.
No; grace is a living thing, because it comes from a living God.
And because it is alive--a living gift of the light, life,
and power of God--its presence and influence in the heart
always teaches us to turn _from_ what is contrary to Him,
and to turn to, look for, long after, pray for, and wait for His further appearing.
Consider the following words of Paul in his letter to Titus:

[.embedded-content-document]
--

__For the grace of God that brings salvation has appeared
to all men, [.underline]#teaching us# that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in the present age,
looking for the blessed hope and glorious appearing
of our great God and Savior Jesus Christ,
who gave Himself for us,
that He might redeem us from every lawless deed and
purify for Himself His own special people,
zealous for good works.__^
footnote:[Titus 2:11-14]

--

Some preach a grace that tolerates ungodliness and winks at worldly lusts.
But the grace that Paul knew taught to deny all ungodliness and worldly lusts,
and to live soberly, righteously, and godly in this present age.
Wherever grace appears,
there are convictions for evil and drawings towards righteousness,
because grace teaches men to depart from the spirit of the
world and to live in the Spirit of Christ.

And is this not what every sincere seeker of truth discovers in their own heart?
Not everybody witnesses miracles in their body, or acts of power in the outward creation.
But do we not all--at least at certain times and
seasons--feel a light that visits us in our darkness,
exposes wrong things that we do not want to see, and calls us out from them?
Who has not, in moments of stillness and sobriety,
received an ability to see a contrast between the evil of their own condition,
and the goodness and purity of God?
Who has not had both good and evil, life and death, plainly set before them,
and heard a still,
small voice inviting them to "`Choose life!`"? Where does this come from?
Who is this teacher?
_This teacher is the grace of God that brings salvation_.

Grace does not save all, because all do not receive it.
But it appears to all, calls to all,
and brings with it salvation for all who will be taught by it.
And any who will listen to the instructions of grace will quickly
discover that it never teaches contrary to the nature of God,
nor to the testimony of Scripture.
For instance,
grace will never teach you that God is unwilling or unable
to overcome all sin in the heart of a Christian.
You may hear such a teaching from man,
but you will neither read it in Scripture nor be taught it by grace.
Nor does grace speak like the false prophets,
who "`heal the wound of God`'s people slightly, saying, '`Peace,
peace!`' when there is no peace.`"^
footnote:[Jeremiah 6:14-8:11; Ezekiel 13:10]
No; grace is a good teacher, and it not only speaks the truth,
but also empowers man to live it.
