== What is Grace?

Before taking up the subject of grace,
it may be helpful to quickly review some of the most important
things that we have already said about law.
First, we defined law as a constant rule or power that never changes,
and that demands obedience or conformity whenever it acts upon something else.
This is true of all kinds of laws, whether they are outward written laws,
natural laws (like gravity), or spiritual laws, like the law of sin and death,
or the law of the Spirit of life in Christ Jesus.

We saw that, in the beginning, there was no need for any outward or written laws,
because the life, power, nature,
and will of God was operating as a law in and over all creation.
As long as creation continued in its proper domain, in submission to its Creator,
all was goodness, righteousness, and joy.
It was only when man stepped out of this happy submission
to God`'s government (called the kingdom of God),
and transgressed His nature and power and righteousness, that an outward law was added.
It was added because of transgressions until the Seed would
come--whose coming was both outward and inward.

We saw that the problem with this outward law, which was given to man in words,
commandments, and requirements, was that it could not give what it described.
It described righteousness, love, and union with God,
but it could not impart these things, and so it was weak and unable to "`make perfect`"^
footnote:[Hebrews 7:19-9:9, 10:1, 11:40]
those who lived by it or under it.
However, what the law could do, and what it had to do by its very nature,
was point out every way that the natural man fell short of the purity, perfection,
and righteous requirement of his Creator.
In itself, the law was "`holy,
just and good,`" but it worked as a "`ministry of
condemnation`" to the transgressing nature,
exposing and condemning everything in man that was contrary to the life and will of God.

Finally,
we saw that this unfortunate relationship between
the law of God and the sinful nature of fallen man,
was compared by Paul to a permanent marriage relationship
that can only be ended by death.
The law cannot die,
because it describes and requires the unchangeable righteousness of God.
But the sinful nature of flesh, or "`the old man,`"^
footnote:[Ephesians 4:22; Colossians 3:9; Romans 6:6]
can be experientially baptized into the death of Christ,
and the soul joined to the One who was raised from the dead,
in order to bear fruit in righteousness.
In this way, the righteous law is never abolished, changed, forgotten, or repealed.
It is rather fulfilled by the righteousness of Christ living
and reigning in those who walk by His Spirit.

Having understood these things concerning the law,
we are in just the right place to understand the gift of God`'s grace,
_because grace is the coming of what the law could not do._
Grace is powerful where the law was weak, and unlike outward rules and regulations,
grace is indeed able to perfect those who draw near to God.

It is of the greatest importance that every Christian rightly
understands and experiences this incredible gift.
I say _rightly_,
because I believe the enemy of man`'s happiness has sought
to disseminate many falsehoods regarding the grace of God,
several of which had already become popular in the days of the first apostles.

What is grace?
Most Christians associate the word grace with a free gift from God.
When I was young,
I remember hearing an older Christian define the
words grace and mercy in the following way:
"`Grace,`" he said, "`is when you get something you _do not_ deserve;
mercy is when you do not get something that you _do_ deserve.`"
I remember at the time being somewhat struck with the profundity of this statement,
but I realized later that it actually told me very little about grace.
Understanding that we do not deserve grace, does not tell us anything about what it is.
Christians sometimes exclaim: "`Grace is the free gift of God!`"
Indeed it is.
But a free gift _of what?_
Much depends upon our understanding of what it is, what it does,
and how we come to experience it.

It is not uncommon today to speak of grace as though it
had something to do with the removal of a law for righteousness.
People often make comments like:
"`Under the law there were strict boundaries and fixed expectations regarding righteousness,
but now Christ`'s death and resurrection have happily
taken all of that away and given us grace.`"
In the mind of many,
the "`grace`" spoken of here is more or less synonymous with _tolerance,_
and for this reason,
the law is frequently contrasted with grace in the sense that one is strict,
and the other is more lenient.
It is thought that law is intolerant,
but grace is much more willing to wink at failures and wrongdoing.
In fact, it has become a popular form of encouragement to say to another,
"`Give yourself some grace!`", meaning, "`Don`'t be so hard on yourself;
everyone makes mistakes.`"

Others make use of Paul`'s expression, being "`under grace`"^
footnote:[Romans 6:14]
as though it referred to a new status or legal position with God,
where all sin is removed from His sight (some say "`past, present and future`"),
or at least where God is less concerned with sin than He was in the days of Moses.
In the mind of these,
the grace of Jesus Christ works somewhat like a giant umbrella that shields
the believer from God`'s searching eyes and unyielding demands.
In fact, it is increasingly common to hear Christians say, "`Thanks to grace,
when God looks at you, He doesn`'t see you at all; He only sees Jesus.`"

But despite the popularity of these ideas,
they really have _nothing_ to do with what the Scriptures affirm about the grace of God.
I mean this quite literally; they have not a single Scripture in their favor.
We have already demonstrated that the righteous law
of God is not to be shielded or softened,
but rather _fulfilled_ by the very nature that it describes.
Jesus`' words are clear:
"`Not one jot or one tittle will by any means pass from the law till all is fulfilled.`"
And Paul insists that,
"`the righteous requirement of the law`" is to be "`_fulfilled_ in us who
do not walk according to the flesh but according to the Spirit.`"

How then should we understand the grace of God?
If you look up every occurrence of the word grace in the New Testament
(something I encourage every Christian to do;
there are about 130 of them),
I believe you cannot help but see that the word grace has
to do with _the power of God freely offered to man,
and effectively working in man._
To offer a very general definition,
the Bible teaches that _grace is the effective working of God`'s power._
And in the majority of these 130 verses,
we see that God`'s grace _comes_ in a very particular way,
and _does_ a very specific thing in the heart of man.
Grace is not a new status.
It is not a legal position.
It has nothing to do with God removing His righteous requirement, with tolerating sin,
or with being unable to see it.
All of this is pure invention.
Grace is the living and effective power of God that works in and upon man.

When speaking of the Child Jesus, Luke writes,
"`And the Child grew and became strong in spirit, filled with wisdom;
and the grace of God was upon Him.`"^
footnote:[Luke 2:40]
Could this possibly mean that a new legal position was upon Jesus?
Or that God was overlooking Jesus`' sins by grace?
Of course not.
Instead, we understand that the living power of God, the effective working of His might,
was in and upon the incarnate Son of God, even when He was a Child.
In Acts 4:33 we read,
"`And with great power the apostles gave witness to the resurrection of the Lord Jesus.
And great grace was upon them all.`"
Clearly the meaning here is that the power of God was manifestly present with them all.
Grace was God`'s power working in their weakness,^
footnote:[See also 2 Corinthians 12:9]
demonstrating what He would do in His own will and by His own strength.
