== A Measure of His Fullness

Consider the following Scripture:

And the Word became flesh and dwelt among us, and we beheld His glory,
the glory as of the only begotten of the Father, full of grace and truth.
John bore witness of Him and cried out, saying, "`This was He of whom I said,
'`He who comes after me is preferred before me,
for He was before me.`'`" And of His fullness we have all received, and grace for grace.
For the law was given through Moses, but grace and truth came through Jesus Christ.^
footnote:[John 1:14-17]

Here John tells us that "`the law was given through Moses.`"
Once again, what was this law that came through Moses?
It was the description and requirement of righteousness
that was given to men because of transgression.
And though it was holy, just, and good in itself,
it was nevertheless weak and unprofitable because
it could not impart the nature that it described;
it could make nothing perfect.
Then John says, "`but grace and truth came through Jesus Christ.`"
What is this grace that comes through Jesus Christ?
Grace is not a description of righteousness in words,
and it most certainly is not the removal or lessening of God`'s righteous requirement.
_Grace is the power of righteousness, the life of righteousness,
the substance and Person of righteousness, given to live, to grow,
and to reign in the soul of man._

Remember Paul`'s words to the Galatians:
"`If there had been a law which could have imparted life,
then righteousness would have been by the law.`"^
footnote:[Galatians 3:21]
We have seen that the written law could not give life,
and for that reason it was called weak and unprofitable.
Grace, however, can give life.
Grace does give life.
In fact, that is precisely what grace is!
It is a gift or measure of the life and power of the One who is righteousness.
Grace is a measure of His fullness.

We also read that the law "`was added because of transgressions,
until the Seed should come to whom the promise was made.`"^
footnote:[Galatians 3:19]
The law exposed transgression, and pointed to the life, nature,
and righteousness of Christ.
It showed the need for Christ, and was "`a tutor to bring us to Christ.`"^
footnote:[Galatians 3:24]
But the actual coming, giving, or sowing of this life-giving Seed is called grace.
Christ the Seed came outwardly, and He also comes inwardly.
Or perhaps it is more accurate to say:
Christ the Seed came outwardly so that He could come inwardly.
The outward work of Christ opened a new and living way in which
every soul could experience the inward work of Christ.

Therefore,
the first and most important thing that we must understand about grace is that
it is the power of God--the effective working of His life and light,
which both came to the world as a Man,
and then was given to all men as an indwelling gift
that can do what the written law could not.
It is a gift of God`'s power, a measure of His life, light, and Spirit,
which comes from the One who is "`full of grace and truth.`"^
footnote:[John 1:14]
"`Of His fullness we have all received, and grace for grace.`"^
footnote:[John 1:16]
