== Removing a Stumbling Block

We have seen that grace is the effectual working of God`'s power in man.
It is not a new position or status, a legal contract,
or a softening of the law for righteousness.
It is the power of God, a measure of His own life, light,
and Spirit that actually fulfills the requirement
of righteousness in man by changing his heart.
Grace removes condemnation, not by removing the requirement of righteousness,
but by forming the righteous life of Jesus Christ in the soul.
Grace is power.
It is the power of a new life, with a new nature.

The law came through Moses,
but the authority and the power _to make righteous_ came through Jesus Christ.
And though this power can be manifested outwardly, though it can create stars, planets,
mountains and oceans, still its greatest manifestation, and its greatest miracle,
is found in the dark heart of fallen man where it
changes sons of wrath into children of light.
The law described righteousness, but grace is the power of righteousness, goodness, life,
and love, planted in the soul by the resurrected Son of God.

Now, with respect to man`'s experience of grace,
it can be compared to the coming of Jesus Christ to His temple,
which had long been a den of robbers; or to the coming of a strong man to his house,
where another had previously possessed His goods.
But both the nature of this coming, and the nature of His increase,
were a "`mystery hidden from ages and from generations,
but now revealed to His saints.`"^
footnote:[Colossians 1:26-27. The context of this
quotation refers to Christ`'s presence in man,
our "`hope of glory.`"
See also 1 Peter 1:10-16,
where we are told that the prophets of old "`inquired and searched carefully,
who prophesied of _the grace that would come to you.`"_
In consideration of which,
Peter instructs us to "`rest your hope fully upon the grace that
is to be brought to you at the revelation of Jesus Christ.`"]

What was this great mystery?
In a word, it was the reality that, though God is a great and mighty King,
He begins His powerful reign like a small stone cut out of a mountain without hands,^
footnote:[Daniel 2:34,45]
like a mustard seed in a garden of other plants, or like a treasure hidden in a field.
This is perhaps the greatest and most important "`mystery of the kingdom of God.`"^
footnote:[Matthew 13:11; Luke 8:10]
Neither Christ`'s outward appearing in Israel, nor His inward appearing in man,
has come like an army with banners,
or like an atomic bomb that demolishes everything in its path.
No;
His coming is like a humble and unpretentious King
who sets His throne right in the midst of His enemies,
and from there extends His rule in those who surrender
their will in the day of His power.
This is the nature of the kingdom declared by David in the famous Ps. 110,
the most frequently quoted Psalm in the New Testament.

[.embedded-content-document]
--

_The LORD said to my Lord, "`Sit at My right hand,
till I make Your enemies Your footstool.`"
The LORD shall send the rod of Your strength out of Zion.
Rule in the midst of Your enemies!
Your people shall volunteer freely in the day of Your power; in the beauties of holiness._

--

The reign of God`'s power does not advance like the kingdoms of this world.
The kings of this world first defeat their enemies,
and then set their throne in a conquered land.
But here we are told that God first sets His King in the midst of His enemies,
and from there sends out "`the rod of His strength,`"
waiting for them to be made a footstool for His feet.
God first anoints His King, sows Him like a living seed into the heart of man,
and then invites him to relinquish his will in the day of His power--that is,
when light dawns in the heart.
These two aspects are always involved in the increase of His kingdom: on the one hand,
there is a voluntary joining to the Lord in the light,
or in "`the day of His power;`" on the other hand,
there is an ongoing destruction of the uncircumcised nature.

It would be beyond my scope here to say much about the unmistakable parallels and pictures
of these spiritual realities given to us in the stories of the Old Testament.
But allow me at least to encourage my reader to peruse
the story of David with these truths in mind.
In so many ways, the beginning, increase,
and reign of David in the outward land of Israel, with all of his battles,
both against Saul and the Philistines,
were pictures of the working of Christ`'s grace in the heart.
The kingdom of David was a God-given illustration of the truth that,
though grace begins as a small anointing, yet it can overcome all enemies,
rescue the willing soul, and fill the land of the heart with the kingdom of God.

=== The Word of Grace

When Paul had been with the church in Ephesus for three years,
he left them with strong warnings,
informing them not only that "`savage wolves`" were coming who would not spare the flock,
but that men would arise from within the church speaking
perverse things to draw away disciples after themselves.
Immediately after this he says:

[.embedded-content-document]
--

__Therefore watch,
and remember that for three years I did not cease
to warn everyone night and day with tears.
So now, brethren, I commend you to God and to the word of His grace,
which is able to build you up and give you an inheritance among all those who are sanctified.__^
footnote:[Acts 20:31-32]

--

Look carefully at what Paul is saying here.
"`Watch, be on your guard!
I am leaving you, but there is something staying behind with you.
Danger is coming both from within and from without,
but there is a power that will remain with you.
I commend you to this power!
I point you to it as your only hope.
It is the Word of His grace, a Seed of His grace, a gift of Christ`'s living power,
which is able to build you up and give you an inheritance
among all those who are sanctified by it.
This grace is your strength, your wisdom, your experience of God`'s salvation.
Love it, and it will grow.
Obey it, and it will build you up.
Submit to it, and it will sanctify you.`"

It seems well worthy of notice in this passage that Paul did _not_ say,
"`Problems are coming, deception is coming, but I commend you to my writings.`"
Or, "`Things are going to get bad,
but I commend you to the leaders and elders that I have appointed over you.`"
Instead,
he commends them all to a Word of grace that (when submitted to)
would never fail to lead and empower them in the way of life.
This grace begins like a little light in the heart, or like a still,
small voice that says, "`'`This is the way,
walk in it,`' whenever you turn to the right hand, or whenever you turn to the left.`"^
footnote:[Isaiah 30:21]
And when we love its light, we begin to feel its power.
We find that it has an anointing from on high to teach,^
footnote:[1 John 2:27]
to cleanse, to change, to put to death and to make alive.
Grace does all things in the believer when it is received and obeyed.
Grace must do all in man, because man can do nothing good apart from grace.

=== A Cross-less Grace

But now, in love to my reader,
and with sincere desires that all will experience
this Word of grace and its work in the heart,
I feel an obligation to remove a couple of common stumbling
blocks out of the way of all sincere seekers of truth.
I take no pleasure in finding fault with wrong ideas,
or in contributing to divisions in the already divided church.
I have a strong aversion to argument,
and generally find debate to be an unfruitful practice in the body of Christ.
However, because we have a very real enemy,
who would love nothing more than for Christians to
end their race with heads full of doctrines,
and hearts entirely void of the life and nature of Christ,
I feel compelled to expose a couple of his most successful misrepresentations.

In the heart of fallen humanity,
there is a prevailing tendency to want to be seen to be better than we truly are.
This unholy desire is naturally in all of us.
In fact, from the very onset of sin,
man has tried to hide his true condition behind a
variety of fig-leaf coverings and theologies.
In consequence,
it has become a very attractive idea in the church today to somehow
possess a righteousness that we do not actually experience or obey,
to consider ourselves sanctified without actually having to change,
or to call ourselves redeemed in the sight of God
even when we are clearly _not_ redeemed from sin,
vanity, foolish talking, lust, and the love of the world,
in the sight of our closest friends.
Man is enamored with the idea that God can _call us_ "`dead to sin,`" even
when our daily choices manifest that we are very much under its power.
We love to hear leaders tell us that God sees us one way,
even when we know that our spouses would say something diametrically different.

This great propensity in the heart of man,
encouraged by the whisperings of an invisible enemy,
has produced a large buffet of doctrines that, in one way or another,
proclaim a kind of "`grace`" that can be possessed
and enjoyed without man having to lose his life,
his will, and his treasure in the flesh.
In other words,
it has created a _cross-less grace_--a grace that does
not crucify the passions and lusts of the first birth;
a grace that covers sin without removing it,
or that frees from the _consequences_ of sin without actually
bringing man out from under its dominion.

These are not minor doctrinal inaccuracies.
This is a _false grace_ that, when believed,
can work in the heart of Christians as an enormous barricade,
obstructing the experience of redemption, silencing the voice of conviction,
and resisting the work of the Spirit of truth.
And I believe it was precisely because of the attractiveness of such doctrines
that the apostles felt constrained to write to the church:
"`Little children, let no one deceive you.
He who practices righteousness is righteous, just as He is righteous.`"^
footnote:[1 John 3:7]
Or, "`What shall we say then?
Shall we continue in sin that grace may abound?
Certainly not!
How shall we who died to sin live any longer in it?`"^
footnote:[Romans 6:1-2]
Or, "`Nevertheless the solid foundation of God stands, having this seal:
'`The Lord knows those who are His,`' and,
'`Let everyone who names the name of Christ depart from iniquity.`'`"^
footnote:[2 Timothy 2:19]

One of the ways that false grace has gained ground in the church is through
the popular idea that everything is finished in us just as soon as we
say the "`sinner`'s prayer,`" or "`accept Jesus into our heart.`"
There are a great many versions of this doctrine,
but the general idea is that God has done all,
and therefore man can do nothing apart from seeing, enjoying,
and resting in what Christ has already accomplished for us.
Some misconstrue Christ`'s final words,
"`It is finished,`" insisting from this declaration that we are already perfect,
and lack only the revelation of what we already are.
This same idea is often set forth with clever phrases like: "`You are already righteous;
you just need to believe it.`"
Or, "`God doesn`'t see your sin; He only sees Christ in you.`"
Or "`It`'s not about doing; it`'s about realizing.`"
Or, "`The problem isn`'t your condition, it`'s your perception.`"
Or, "`You are as righteous as you will ever be; now just act like who you already are.`"

Again, there is something very appealing to the flesh in statements like these,
but the truth of the matter is that grace has _nothing_
to do with an imperceptible change in status,
or with a lens through which God sees us differently than we really are.
Consider for a moment how many verses in both the Old and New Testaments tell us plainly,
and in a variety of different expressions, that God '`searches the heart, tests the mind,
and gives every man according to his ways, according to the fruit of his doings`'?^
footnote:[Jeremiah 17:10]
How many Scriptures warn us that God sees
"`the thoughts and intentions of the heart,`" and that "`all things are
open and laid bare to the eyes of Him with whom we have to do.`"^
footnote:[Hebrews 4:12-13]
Are not _Christians_ warned in many ways that God will "`bring to light
the things hidden in the darkness and disclose the motives of men`'s hearts,`"^
footnote:[1 Corinthians 4:5]
and that each man "`will receive the things done in the body,
according to what he has done, whether good or bad`"?^
footnote:[2 Corinthians 5:10]
Were there not many in the first-century
church who claimed to be spiritually rich and in need of nothing,
but were in fact "`wretched and miserable and poor and blind and naked.`"^
footnote:[Revelation 3:17]
And did not Christ warn that "`many`"^
footnote:[Matthew 7:22]
would claim to belong to Him, to have believed His doctrine and ministered in His name,
and yet be rejected with these surprising words: "`I never knew you; depart from Me,
you who practice lawlessness!`"?^
footnote:[Matthew 7:23]
The New Testament abounds with warnings of this kind.
But where are the Scriptures that tell us that God cannot see our sin,
or that man can possess a righteousness that he does not obey,
or in which he does not live?

The simple and manifest truth (to which every honest
conscience must bear witness) is that,
if sin remains alive in us as a leader, a ruling principle, and a source of our action,
then it is not yet dead--no matter what we affirm about ourselves.
In the incontrovertible words of Christ, "`Truly, truly, I say to you,
everyone who commits sin is the slave of sin.`"^
footnote:[John 8:34]
We cannot claim to be something that we are not living.
Grace does not give us this power.
The power of grace is real and free and wonderful,
but it is not power to see ourselves differently than we are;
it is power to make us different than we are, to change us, cleanse us,
and create in us a new heart.

Though there are certainly Scriptures that speak of being justified by grace,
this is not a grace that justifies man _in sin._
Grace justifies only the heart that receives and obeys it.
Let me back up a bit and explain briefly what I mean.

The purpose of Christ`'s coming as a Man, the reason for His sinless life,
perfect obedience, sorrows and sufferings, death, burial, resurrection, and ascension,
was because mankind in Adam had died to the life of God,
and was left bound _in nature_ to the powers of sin and death.
Adam, and all his posterity who bore his image and likeness,
were trapped by their very birth in a sort of Egyptian bondage,
and under such a cruel taskmaster,
that far exceeded the outward pictures that God later used to depict
this condition in the story of Israel`'s exodus.

Like Moses coming into Egypt, the Son of God came into this world,
and into our condition, in order to make a way out of it;
and this was accomplished in primarily these two ways: first,
by Christ`'s overcoming everything that had overcome
Adam and separated him from his Creator;
and second,
by Christ then sharing His overcoming life with the souls of a redeemed humanity.
All the types and shadows in the Old Testament, all four Gospels,
and all of the letters of the apostles,
declare and magnify the incredible truths of this miraculous salvation.

In indescribable love,
the Son of God came in the nature of man (being fully God and fully Man),
and conquered every obstacle in the way of man`'s return to Paradise.
In perfect submission to the will and Spirit of God,
the Lamb of God overcame every inclination of self-will and independence,
every human desire and appetite that would turn man`'s heart from his Maker,
every form of weakness, hunger, thirst, and anxiety, every kind of temptation,
persecution, demonic attack, the greatest inward and outward distresses,
the greatest emotional and bodily pains, and ultimately the abandonment of God,
physical death, and the grave.
All of this was accomplished, and all of this was necessary,
because man had brought himself under the power of every one of these things,
and all of them were like gates and bars that prevented
man`'s return into oneness with his Creator.
This was the prayer of Christ on the night before He was betrayed,
that "`they all may be one, as You, Father, are in Me, and I in You;
that they also may be one in Us.`"^
footnote:[John 17:21]
This was the mission He was sent to accomplish: to unite where Adam had separated,
to "`raise up the waste places`"^
footnote:[See Isaiah 44:26,51:3, 52:9, 58:12]
and restore all that Adam had destroyed.
Thus the Son of God became a Son of Man who, in our fallen condition, but without sin,
and in perfect submission to His Father,
"`became the author of eternal salvation to all who obey Him.`"^
footnote:[Hebrews 5:9]

[.embedded-content-document]
--

__For it was fitting for Him, for whom are all things and by whom are all things,
in bringing many sons to glory,
to make the captain of their salvation perfect through sufferings.
For both He who sanctifies and those who are being sanctified are all of one,
for which reason He is not ashamed to call them brethren... Therefore,
since the children share in flesh and blood,
He Himself likewise also partook of the same,
that through death He might render powerless him who had the power of death, that is,
the devil, and might free those who through fear
of death were subject to slavery all their lives.__^
footnote:[Hebrews 2:10-11, 14-15]

--

But this is just the half of what Christ has done for us!
This is just the door unlocked, the Red Sea parted,
and a new and living way cast up in the wilderness.
Were this all that Christ accomplished on our behalf,
it would indeed be a miracle of love, but not a single human being could follow Him out.
Without a birth of His victorious Spirit,
without the gift of a nature that was stronger than flesh,
man could only admire Christ`'s victory from afar.
But when this Conqueror had overcome sin and death,
and returned to the right hand of His Father in heaven,
He then poured out His overcoming Spirit on all flesh,
and visited every human being with a power (called _grace_)
that can both see in His light and follow in His footsteps.
Christ was the firstborn from among the dead,
the Head that opened the womb of death and the grave.
But this Head has a body in the earth that can be born of His life, grow in His nature,
and overcome by His power.
For this reason He declares to the church: "`He who overcomes,
I will grant to him to sit down with Me on My throne,
as I also overcame and sat down with My Father on His throne.`"^
footnote:[Revelation 3:21]

Jesus did not come as a Man, become obedient unto death, and suffer on a cross,
so that God could avenge His anger on an innocent substitute,
or receive sufficient satisfaction for His offended authority.
I understand that these are popular ideas,
but I see nothing in Scripture that supports such a view of God`'s nature,
nor such a motivation and means of man`'s salvation.
It was not God`'s anger that sent Christ into the world, but His love;
and that love came, suffered, died,
and rose again in order to reopen the everlasting gates,
and to share the "`power of an indestructible life`"^
footnote:[Hebrews 7:16]
with all who would receive it.
This is what Christ finished two-thousand years ago.
And this redeeming power of our overcoming Savior
that sanctifies us even as He was sanctified,^
footnote:[John 17:19; Hebrews 2:11]
this power that overcomes by His overcoming nature, is called _the grace of God._
This is the "`Spirit of grace`"^
footnote:[Zechariah 12:10; Hebrews 10:29]
that is able to work in the body of Christ the same
victory that it first accomplished in the Head.

Now, it is entirely true that man is justified by grace,
and not by works of the flesh or works of the law.
But we must be careful not to invent our own meanings of these words.
If anyone is claiming to be a partaker of grace,
and yet is not living _in and under the government of grace,_
then this betrays a great misunderstanding--the same misunderstanding
that was rejected by Paul in these words:
"`Shall we sin because we are not under law but under grace?
May it never be!`"^
footnote:[Romans 6:15]
Christ has indeed finished all that is necessary, and all that is possible,
for man to experience the benefit of His redemptive work.
He has loved us first, come in our image, offered Himself as a sacrifice,
and overcome sin and death so that repentance and forgiveness of
sin can be offered in His name to all the nations of the world.
He has torn the veil that leads to the Holy of Holies,
opened a door out of inward slavery and darkness,
and cast up a new and living way for the redeemed to walk upon.
He has stripped the devil of his right to hold souls,
and taken away man`'s debt or obligation to the flesh.^
footnote:[Romans 8:12]
He has become the perfect captain of our salvation,
removed the immovable wall of partition,
and brought us into covenant with God by sowing a seed of His own grace, light,
and Spirit in the soil of our hearts.
Everything impossible has been done, the wedding feast is ready,
the invitations are sent out,
and every human being has been empowered to "`work out his salvation with fear and trembling.`"^
footnote:[Philippians 2:12]
But all of this was accomplished,
not so that God could call us something that we are not,
but so that He could make us '`holy, for the Lord our God is holy.`'^
footnote:[Leviticus 11:44-45; 19:2; 20:26; 1 Peter 1:15-16; Matthew 5:48]

Grace has come as power from on high.
But man must _abide_ in this power if he wants to experience its work,
continually uniting his will to this gift and denying all that is contrary to it.
It is a truth beyond question that man is justified by grace and not by works;
but there is no grace that justifies man _in sin._
Grace visits man, calls him out of sin,
and empowers him to abide in the overcoming Spirit of Christ.
It is like a strong hand that reaches into Egypt
and pulls out all who will submit to its rule.
But it is only those who will be ruled by grace, who will continue under its government,
and turn their back on the flesh and the world, that are justified, sanctified,
and glorified by it.
This is why Paul and Barnabas persuaded the churches "`to _continue_ in the grace of God,`"^
footnote:[Acts 13:43]
and why the author of Hebrews warned his readers to "`look
carefully lest anyone fall short of the grace of God,`"^
footnote:[Hebrews 12:15]
and to never "`insult the Spirit of grace.`"^
footnote:[Hebrews 10:29]

At no point in this miraculous gospel does God reckon a man to
be something contrary to the nature in which he is living,
nor does God become blind to the sins of mankind.
It is true--and worthy of thanksgiving and praise--that even a newly converted sinner,
upon turning from sin and self, and surrendering his life to the gift of grace,
is justified from past sin, _because his will has then gone out from it._
That is to say, when God sees that we have changed leaders,
ceased to follow sin and Satan,
and become "`obedient from the heart`" to the teachings
of grace to which we have been delivered,^
footnote:[See Romans 6:17 "`But God be thanked that though you were slaves of sin,
yet you obeyed from the heart that form of teaching to which you were delivered.`"]
then we are forgiven and justified from the sin that we now hate.
Here the believer is justified by grace,
and now he must diligently continue in grace to make his calling and election sure.^
footnote:[2 Peter 1:10]
But if the heart will not continue under the Hand
that visited and called him out of Egypt,
if the will does not abide in submission to the power that justifies,
but rather "`turns the grace of our God into licentiousness,`"^
footnote:[Jude 1:4]
then this is what the apostle calls "`falling from grace,`"^
footnote:[Galatians 5:4]
or "`receiving the grace of God in vain.`"^
footnote:[2 Corinthians 6:1]

It is a dangerous untruth when Christians are told that they have arrived at the journey`'s
end when in fact they have often only just begun to experience the work of grace.
And it is not the true work of the ministry to speak comfort, reassurance,
and safety to a people who still feel themselves to be slaves to sin,
living the will and way of the first birth, in the lusts of the eyes,
the lusts of the flesh, and the pride of life.
The Scriptures offer great encouragement and comfort to those who
are carefully and constantly living under the grace of God,
submitting their will to its guiding, teaching, and empowering work.
But in no verse are we encouraged to rest in yesterday`'s grace.
Every single epistle of Paul both begins and ends with an expression
of desire that his readers continue to grow in the grace of God.
And this is because Paul knew grace to be a growing power,
a living seed of Christ`'s kingdom, appointed by God to crucify all selfishness, pride,
envy, anger, fear and lust, and to fill the soul with the power of Jesus`' light, life,
and love.

Permit me to address my reader in the words of the author of Hebrews: "`I appeal to you,
brethren, bear with the word of exhortation:`"^
footnote:[Hebrews 13:22]
Please do not content yourself with a name that you live, if you are really dead;^
footnote:[Revelation 3:1]
or with a claim that grace has done all,
if your heart still finds its home and its treasure in this world.
Do not sit down in what Christ has done for you outwardly,
if you have experienced little or nothing of what He desires to do inwardly.
This has been a pervading error in the church since the time of the Reformation.
The masses cry out, "`Grace has done everything!`", but a still,
small voice continually whispers in the heart:
"`But what have you allowed grace to do in you?`"
