== Removing a Stumbling Block

We have seen that grace is the effectual working of God`'s power in man.
It is not a new position or status, a legal contract,
or a softening of the law for righteousness.
It is the power of God, a measure of His own life, light,
and Spirit that actually fulfills the requirement
of righteousness in man by changing his heart.
Grace removes condemnation, not by removing the requirement of righteousness,
but by forming the righteous life of Jesus Christ in the soul.
Grace is power.
It is the power of a new life, with a new nature.

The law came through Moses,
but the authority and the power _to make righteous_ came through Jesus Christ.
And though this power can be manifested outwardly, though it can create stars, planets,
mountains and oceans, still its greatest manifestation, and its greatest miracle,
is found in the dark heart of fallen man where it
changes sons of wrath into children of light.
The law described righteousness, but grace is the power of righteousness, goodness, life,
and love, planted in the soul by the resurrected Son of God.

Now, with respect to man`'s experience of grace,
it can be compared to the coming of Jesus Christ to His temple,
which had long been a den of robbers; or to the coming of a strong man to his house,
where another had previously possessed His goods.
But both the nature of this coming, and the nature of His increase,
were a "`mystery hidden from ages and from generations,
but now revealed to His saints.`"^
footnote:[Colossians 1:26-27. The context of this
quotation refers to Christ`'s presence in man,
our "`hope of glory.`"
See also 1 Peter 1:10-16,
where we are told that the prophets of old "`inquired and searched carefully,
who prophesied of _the grace that would come to you.`"_
In consideration of which,
Peter instructs us to "`rest your hope fully upon the grace that
is to be brought to you at the revelation of Jesus Christ.`"]

What was this great mystery?
In a word, it was the reality that, though God is a great and mighty King,
He begins His powerful reign like a small stone cut out of a mountain without hands,^
footnote:[Daniel 2:34,45]
like a mustard seed in a garden of other plants, or like a treasure hidden in a field.
This is perhaps the greatest and most important "`mystery of the kingdom of God.`"^
footnote:[Matthew 13:11; Luke 8:10]
Neither Christ`'s outward appearing in Israel, nor His inward appearing in man,
has come like an army with banners,
or like an atomic bomb that demolishes everything in its path.
No;
His coming is like a humble and unpretentious King
who sets His throne right in the midst of His enemies,
and from there extends His rule in those who surrender
their will in the day of His power.
This is the nature of the kingdom declared by David in the famous Ps. 110,
the most frequently quoted Psalm in the New Testament.

_The LORD said to my Lord, "`Sit at My right hand,
till I make Your enemies Your footstool.`"
The LORD shall send the rod of Your strength out of Zion.
Rule in the midst of Your enemies!
Your people shall volunteer freely in the day of Your power; in the beauties of holiness._

The reign of God`'s power does not advance like the kingdoms of this world.
The kings of this world first defeat their enemies,
and then set their throne in a conquered land.
But here we are told that God first sets His King in the midst of His enemies,
and from there sends out "`the rod of His strength,`"
waiting for them to be made a footstool for His feet.
God first anoints His King, sows Him like a living seed into the heart of man,
and then invites him to relinquish his will in the day of His power--that is,
when light dawns in the heart.
These two aspects are always involved in the increase of His kingdom: on the one hand,
there is a voluntary joining to the Lord in the light,
or in "`the day of His power;`" on the other hand,
there is an ongoing destruction of the uncircumcised nature.

It would be beyond my scope here to say much about the unmistakable parallels and pictures
of these spiritual realities given to us in the stories of the Old Testament.
But allow me at least to encourage my reader to peruse
the story of David with these truths in mind.
In so many ways, the beginning, increase,
and reign of David in the outward land of Israel, with all of his battles,
both against Saul and the Philistines,
were pictures of the working of Christ`'s grace in the heart.
The kingdom of David was a God-given illustration of the truth that,
though grace begins as a small anointing, yet it can overcome all enemies,
rescue the willing soul, and fill the land of the heart with the kingdom of God.
