== The Word of Grace

When Paul had been with the church in Ephesus for three years,
he left them with strong warnings,
informing them not only that "`savage wolves`" were coming who would not spare the flock,
but that men would arise from within the church speaking
perverse things to draw away disciples after themselves.
Immediately after this he says:

Therefore watch,
and remember that for three years I did not cease
to warn everyone night and day with tears.
So now, brethren, I commend you to God and to the word of His grace,
which is able to build you up and give you an inheritance among all those who are sanctified.^
footnote:[Acts 20:31-32]

Look carefully at what Paul is saying here.
"`Watch, be on your guard!
I am leaving you, but there is something staying behind with you.
Danger is coming both from within and from without,
but there is a power that will remain with you.
I commend you to this power!
I point you to it as your only hope.
It is the Word of His grace, a Seed of His grace, a gift of Christ`'s living power,
which is able to build you up and give you an inheritance
among all those who are sanctified by it.
This grace is your strength, your wisdom, your experience of God`'s salvation.
Love it, and it will grow.
Obey it, and it will build you up.
Submit to it, and it will sanctify you.`"

It seems well worthy of notice in this passage that Paul did not say,
"`Problems are coming, deception is coming, but I commend you to my writings.`"
Or, "`Things are going to get bad,
but I commend you to the leaders and elders that I have appointed over you.`"
Instead,
he commends them all to a Word of grace that (when submitted to)
would never fail to lead and empower them in the way of life.
This grace begins like a little light in the heart, or like a still,
small voice that says, "`'`This is the way,
walk in it,`' whenever you turn to the right hand, or whenever you turn to the left.`"^
footnote:[Isaiah 30:21]
And when we love its light, we begin to feel its power.
We find that it has an anointing from on high to teach,^
footnote:[1 John 2:27]
to cleanse, to change, to put to death and to make alive.
Grace does all things in the believer when it is received and obeyed.
Grace must do all in man, because man can do nothing good apart from grace.
