== Grace Must Reign

Speaking from my own regrettable experience, I know that it is easy to talk about grace,
sing about grace, and celebrate grace,
even while living a life that is contrary in nature to its power and purpose.
This is not uncommon.
There is at present a great assortment of definitions
and opinions about the grace of God,
and the range of ideas on this subject can be confusing.
But I have come to see that every _false_ idea about grace has this one thing in common:
it affirms that we can possess and enjoy the blessings of God without losing our life,
our will, and our treasure in the flesh.
In other words,
it is a grace that does not crucify the passions and desires of the first birth,
does not take our heart out of the world, nor the world out of our heart,
and does not empower us to live soberly, righteously, and godly in the present age.
It is a grace that saves from the _consequences_ of sin, without saving from the power,
pleasure, and reign of sin in the heart.
But this is a grace that the Scriptures will not allow.
Notice Paul`'s words in Romans chapter 5:

_For as by one man`'s disobedience many were made sinners,
so also by one Man`'s obedience many will be made righteous.
Moreover the law entered that the offense might abound.
But where sin abounded, grace abounded much more, so that as sin reigned in death,
even so grace might reign through righteousness to
eternal life through Jesus Christ our Lord._

Paul first reminds us that "`the law entered that the offense might abound.`"
The meaning of this should be clear to us now as
we have seen how the written law could manifest sin,
but had no power to remove it.
The law entered in order to _describe_ righteousness, and to _require_ righteousness,
but because it could not _provide_ righteousness,
it only caused offenses against righteousness to abound.

Then we are told, "`But where sin abounded, grace abounded much more.`"
Where did sin abound?
One could argue that sin abounded in the world,
and therefore grace came to the world through Jesus Christ.
Certainly this is true.
But, because of the immediate context,
and the subject matter of the following three chapters,
it seems clear that the word "`where`" is meant to point
the reader more specifically to the heart of man.
Sin did not primarily abound in outward things; it abounded _in_ man.
That is where the disease was found.
There the law of sin and death was producing its fruits unto death.
There the written law could only expose and condemn what it could not change.
And it is there also that grace abounds much more,
or in a way that is even greater and stronger than the abounding of sin.

Here we come to the heart of Paul`'s argument: "`So that as sin reigned in death,
even so grace might reign through righteousness to
eternal life through Jesus Christ our Lord.`"
If we give these words the attention they deserve,
it seems to me that this verse alone could put an end to all misunderstandings
regarding the nature and purpose of the grace of God.
Because here, as clearly as words can do it,
Paul says that grace _should reign_ in man through the nature of righteousness,
even as sin has formerly reigned in death.

Grace is meant to reign in man just as sin has reigned!
But how did sin reign?
I believe we all know too well the answer to this question.
Sin has reigned in all of us in a way that is evident and unmistakable.
Its kingdom is subtle and deceptive, but it is not invisible or difficult to perceive.
There is no doubting or debating whether sin is a power,
or whether we have experienced its dominion,
because we have all felt its strength in our minds, its influence in our desires,
and its fruits in our lives.
We have felt it changing our perspective, changing our direction, enticing,
pushing and pulling, first inflaming desires,
and then leaving us disappointed and embarrassed as it poisons our lives.
The reign of sin in man is perhaps the most demonstrable thing in all of the world.
To observe it, we need only peer out the window, read the news, talk to a neighbor,
or look into our own heart.
It has roots and vines wrapped around all that man does.
It causes all men to dance behind its pipe,
leading them on toward one form or another of darkness, deception, emptiness, and shame.
He who denies it has already fallen under its power.

But if we only understand this much,
we understand enough to know exactly how grace should reign in man,
and how it should abound much more where sin has abounded.
Because, how can sin reign in all of these powerful, discernible,
heart and life-transforming ways, and grace not be able to do the same?
How can a Christian confess that sin touches everything, pulls and pushes, grows,
fills and defiles from the inside out,
but then say that grace can be possessed and enjoyed without changing our heart?
Paul says that where sin abounded, grace abounds "`much _more_,`" not "`much _less_.`"
Is sin an inward reigning nature, and grace just an outward legal position?
Does sin destroy a person`'s heart and life,
and grace only forgive the mess that sin has made?

No; grace also is an inward nature, a living power,
given to take back the land of the heart from the reign of sin.
The true grace of God also pushes and pulls, draws and teaches, fills and spreads,
changes our perspective, our heart, and our course.
It cleans where sin has defiled.
It speaks truth where men have believed lies.
It comes to all men bringing salvation,
and teaches them to deny ungodliness and worldly lust.
It awakens the slave that sleeps in Egypt, empowers him to leave,
and daily leads him towards the Land of Promise.
The power of grace can be as demonstrable and undeniable in the lives
of Christians as the power of sin is in the people of the world.

In 1 Corinthians 15:10, Paul says, "`But by the grace of God I am what I am,
and His grace toward me was not in vain; but I labored more abundantly than they all,
yet not I, but the grace of God which was with me.`"
In 1 Timothy 1:14 he tells us, "`The grace of our Lord was exceedingly abundant,
with faith and love which are in Christ Jesus.`"
Clearly, the grace of God was changing Paul`'s heart,
working mightily both in him and through him as he persevered in it.
And though we are not all called to be apostles and prophets,
we are indeed all called to walk in the faith and love which are in Christ Jesus.
Every single believer is called to put off the old man,
to be renewed in the spirit of their mind, and to put on the new man.
We are called to die to self, to be crucified to the world, to walk in the Spirit,
"`to do nothing through selfish ambition or conceit,`"^
footnote:[Philippians 2:3]
to "`be perfect as our heavenly Father is perfect.`"^
footnote:[Matthew 5:48]
This requires power!
It requires the effective working of a nature that reigns
and abounds in man where sin did reign and abound.
And this is why we must understand both what grace is, and how it is experienced.

Returning to sin for a moment, how does it begin its reign in man?
Of course there is a seed or nature of sin in us even from birth.
We all come into this world in the image and likeness of our fallen parents,
and even in infancy our hearts can feel the stirring and pulling
of a nature that is contrary to God`'s righteousness and will.
But the question here is not concerning the mere presence of sin in man,
but rather its reign or dominion, the way that it grows and governs a person,
both inwardly and outwardly.
How does this begin and increase?

With a little reflection, we can all answer this question.
We do not experience the coming of sin`'s power to be like an overwhelming flood,
or like a tyrant that suddenly seizes command and overthrows our will.
On the contrary, sin begins as a thought--a mere desire.
The world, the flesh, or the serpent presents an image before the view of the mind,
together with the lie that possessing it will satisfy our desire
and remove the uncomfortable sense of longing and lack.
And when the will consents to this desire, or willingly joins to this thought,
_then_ (and not before) sin is conceived and its power begins to gain ground.
It is only when the will of the soul _turns its attention,
and voluntarily unites_ to the evil desire, that the seed of sin obtains a stronghold,
begins to grow, and gains inertia in the mind.
This, repeated again and again, is how its reign increases in man to bring forth death.
Consider the words of James in chapter 1:13-15:

_Let no one say when he is tempted,
"`I am tempted by God;`" for God cannot be tempted by evil,
nor does He Himself tempt anyone.
But each one is tempted when he is drawn away by his own desires and enticed.
Then, when desire has conceived, it gives birth to sin; and sin, when it is full-grown,
brings forth death._

When does desire conceive and give birth to sin?
Again, when the will of the soul voluntarily unites to it.
Sin is the child of two parents: 1) an evil thought or desire,
and 2) man`'s consenting will.
It is not sin to be tempted, or to have our attention attracted by thoughts, desires,
suggestions of the flesh, or lies of the enemy.
Jesus Himself "`was in all points tempted as we are, yet without sin.`"^
footnote:[Hebrews 4:15]
But one thing that Jesus never did was unite His will to a temptation,
and thus sin never found a place in Him.
It is for this reason that, just prior to the cross,
and having lived more than thirty-three years upon the earth as a Man, He could say,
"`The ruler of this world is coming, and he has nothing in Me.`"^
footnote:[John 14:30]
That is to say, "`The ruler of this world is coming,
but his nature has never been born in Me;
I have never once joined my will to his thoughts.`"

Therefore,
though sin is present as a seed or an innate nature in man from the time of his birth,
yet its power, or '`abounding reign,`' grows in response to the activity of our will.
When we welcome the appearing of evil thoughts and desires, entertain their enticements,
and voluntarily join to their increasing suggestions and promises,
sin is felt to have a snowball effect in our hearts.
It gains ground, gathers speed, weight, and size,
until its influence upon the will seems almost irresistible.
In some, sin seems to rule nearly unhindered,
because they have repressed and grieved the only power that opposes its progress.
This is a dreadful condition of slavery,
and all who persist in it will find the wages of sin to be spiritual death.

But the reason I mention these things is not to glorify the power of sin,
but rather to explain and glorify the power of grace.
Because again, "`Where sin abounded,
grace abounded much more, so that as sin reigned in death,
even so grace might reign through righteousness.`"
Grace also has a seed in man,
a seed that is sown in the heart by the One who is "`full of grace and truth;`"^
footnote:[John 1:14]
and "`of His fullness we have all received, and grace for grace.`"^
footnote:[John 1:16]
The good Sower has gone out and sown a measure of His fullness into every kind of soil,
and this is the reason why grace can abound where sin has abounded.
This gift of Christ`'s Spirit--His grace in the heart--is the ground of our hope,
and the reason why Peter says,
He "`has begotten us again to a living hope through
the resurrection of Jesus Christ from the dead.`"^
footnote:[1 Peter 1:3]

But how does the soul grow in grace?
Or you could ask, how does grace grow in the soul?
Grace is a superior power, an even stronger nature than that of sin,
but its growth in man also depends upon the activity of the will.
I do not mean to say that man`'s will can create it or add anything to it.
But both Scripture and experience demonstrate beyond doubt that what we turn to, look to,
unite with, follow,
and obey greatly affects what we experience of both of these natures.^
footnote:[Consider the words of Dionysius Freher (1649-1728)
-- "`It is a constant and unalterable truth,
that whatever the mind, will, and desire are busied with, the same is drawn into man,
and the soul is thereby made alike unto it.
By what it is fed, entertained and nourished, its life and image grows in conformity.
So that when man`'s mind, will and desire, going downward, were busied with shadowy,
dark, weak, earthly, dead, and impure things,
what else could have been his portion acquired thereby but earthiness in the body,
defilement in the soul, and death in the spirit?--for he fixed his eyes on such things,
and fed upon them with the mouth of his desire.
But when, on the contrary, by the power restored unto him through Jesus Christ, his mind,
will and desire goes upwards, and is busied with light and life,
and with heavenly pure substantial objects,
how can it fall out with him otherwise than according to the words of the apostle,
saying: '`We all, with unveiled face, beholding as in a mirror the glory of the Lord,
are being transformed into the same image from glory to glory,
just as by the Spirit of the Lord.`'`"]

First, grace "`appears`" within as a gift from heaven.
"`The grace of God that brings salvation has appeared to all men.`"^
footnote:[Titus 2:11]
A measure of God`'s light visits man in darkness,
giving him a sight and sense (be it ever so small) of heavenly truth,
along with a mustard seed of power to obey.
God`'s grace finds us in perfect helplessness and loves us first.
In the language of Ezekiel: "`I passed by you and saw you struggling in your own blood,
I said to you in your blood, '`Live!`' Yes, I said to you in your blood, '`Live!`'`"^
footnote:[Ezekiel 16:6]
Like Moses sent to Egypt, or the angels sent into Sodom and Gomorrah,
grace comes and awakens, warns, invites, and empowers to leave.
This is the beginning of God`'s "`working in us both
to will and to do for His good pleasure.`"^
footnote:[Philippians 2:13]
This is the day of small things, the talent put into the hand.
And when the will unites to this free gift, loves its appearing,
agrees with its testimony, and yields to its attraction,
grace then finds room within to grow, to abound, and in time,
to "`reign through righteousness to eternal life through Jesus Christ our Lord.`"

But it is of the greatest importance that we do not overlook the _beginnings_ of grace.
Because just as sin began its kingdom with mere thoughts
and desires that attract towards self,
so grace begins its reign with thoughts and desires that draw the heart towards God.
I do not mean voices, visions, or profound revelations.
Grace can certainly be the author of these things as well.
But I speak now only of those heavenly inclinations, godly convictions,
desires after purity, and thoughts of a better way to live,
that from time to time make an appearance in the mind of man.
I speak of the little checks and reproofs for selfishness, vanity, pride,
and dishonesty that everyone feels throughout every normal day.
There are times when we cannot help but sigh under the burden of sin,
when we feel repulsion towards evil and immorality,
or when our hearts feel drawn beyond the things of time.
These thoughts and feelings come down from above;
they do not originate in the fallen heart of man.
They are gifts of grace from the Father of lights,
and are good and perfect according to their kind.

Were it not for grace, all mankind would be confined to one birth.
In fact, this is the state of all other terrestrial beings.
I do not mean that all creatures of this world live in sin,
or in a will that is contrary to their Creator.
I mean simply that all created beings, besides man, experience only one nature.
A mule is perfectly content to remain a mule until its end.
It never feels convictions for stubbornness, or inward reproofs for not sharing its oats.
A fox is not burdened in conscience for stealing a hen.
A goose does not feel an aversion to vice,
or a secret hope that one day it will be free from the vanity of this world.
But a man feels all these things because, in the mercy of God,
grace introduces another nature^
footnote:[2 Peter 1:4]
that calls man out of his own.^
footnote:[See here the fulfillment of every exodus story (i.e. that of Abraham, Lot,
Israel, Rahab,
etc.) that appears in Scripture--a work of grace by which
God enters into man in order to bring man into God.
Deuteronomy 4:34 "`Or did God ever try to go and _take
for Himself a nation from the midst of another nation,_
by trials, by signs, by wonders, by war, by a mighty hand and an outstretched arm,
and by great terrors,
according to all that the LORD your God did for you in Egypt before your eyes?`"]
Were it not for grace, man would live and die undisturbed in his first birth,
where "`every intent of the thoughts of his heart was only evil continually.`"^
footnote:[Genesis 6:5]
This is the condition of man in his fall,
and there is nothing in him or of him that can go out from himself.
But grace brings a living Word very near unto man--into his heart and
his mouth--and by it God not only sets life and death before every soul,^
footnote:[See Deuteronomy 30:11-20, and Romans 10:5-8]
but also cries out: "`Choose life over death!
Choose grace over nature!`"

This Word of grace, as we have already seen,
is that gift of power to which Paul commended the church in Ephesus.
All of Paul`'s hope for their preservation, growth, and sanctification rested in it.
It is a measure of God`'s own light, a seed of His Spirit, a gift of His implanted Word,
and therefore the origin of every _truly_ good thought.
From grace comes every conviction of evil, every aversion to vice,
every longing for purity, every hope of escaping vanity,
and every humble desire to know and walk with God.
Grace does much more than produce thoughts and desires,
but this is where its reign begins.

Grace calls to man through convictions for evil.
It knocks at his door with good thoughts and desires.
It appears as a teacher, and offers power to obey.
But just as with sin, _its power is experienced in the submission of our will._
It is when the will unites to sinful thoughts and desires that we begin to feel its power.
It is the will`'s joining to temptations that brings man under its government.
And in just the same way,
it is when the will of man unites to grace (in the ability that it supplies),
when we love its testimony, bow low before it, embrace its judgments,
and practice the truth that we see in its light,
that grace finds a home and its kingdom begins.
Here is where the snowball starts to roll, so to speak.
Here is where the sailor can raise his sail to catch the wind.

Now, to avoid all misunderstanding and to answer a common objection,
allow me to say that this uniting of our will and submission
of our lives to the grace that teaches and convicts within,
is neither legalism nor works of the flesh, but simple obedience to the Spirit of Truth.
How else are we meant to "`live in the Spirit`"^
footnote:[Galatians 5:24-25]
and "`walk in the Spirit,`"^
footnote:[Galatians 5:16,25]
apart from a continual subjection of our will to the guidance of the Spirit?
Is there a way to deny ourselves, take up our cross, and follow Christ,
without a diligent surrender of our will?
Certainly not.
For Paul writes emphatically to the church in Rome:
"`If you live according to the flesh you will die;
but if by the Spirit you put to death the deeds of the body, you will live.
For as many as are led by the Spirit of God, these are sons of God.`"^
footnote:[Romans 8:12-13]

If you forget everything else you have read in this book,
my hope is that you will remember this one thing:
that grace is the power of God that redeems the soul of man, crucifies the nature of sin,
makes "`all things new, and all things of God;`"^
footnote:[2 Corinthians 5:17-18]
but the experience of its reign is found as the will unites and the heart continually
submits to even the first and faintest manifestations of His nature.
The power of God can display itself in all sorts of ways,
but for a heart to experience redemption,
for a man to "`grow in the grace and knowledge of our Lord and Savior Jesus Christ,`"^
footnote:[2 Peter 3:18]
he must surrender the first birth at every appearing of the second.
This is presenting ourselves as "`a living sacrifice;`"
this is the Christian`'s "`reasonable service.`"^
footnote:[Romans 12:1]
This is how the heart lives under grace, and how grace spreads over man,
to reign in and over all.

But when our experience of grace is small, we are then most apt to turn aside.
When we are not accustomed to following its voice and continually yielding to its light,
and when "`the cares of this world, the deceitfulness of riches,
and the desires for other things`"^
footnote:[Mark 4:19]
feel stronger in our hearts than the teachings of grace,
we stand in great danger of coming out from under its reign.
This is the case of so many poor souls who are visited by grace and, like Abraham,
hear a call to "`get out of your country, from your family and from your father`'s house,
to a land that I will show you.`"^
footnote:[Genesis 12:1]
They receive the Word of grace with joy,
but because they do not become rooted and grounded in the surrender of their will,
they "`endure only for a while.`"^
footnote:[Matthew 13:21]
They begin to build a tower, but are not able to finish.
They start the Christian life with a strong battle cry,
but soon after "`send out a delegation and ask for terms of peace,`"^
footnote:[Luke 14:32]
joining the ranks of those who believe in grace, defend grace,
and yet remain strangers to its power.

And this is precisely why the apostles exhorted new
believers to "`continue`" in the grace of God,
and pleaded with them not to receive the grace of God in vain.
The New Testament speaks of grace not merely as a gift to receive,
but as a power or government under which we must continually live.
For this reason we are warned against setting aside the grace of God, falling from grace,
insulting the Spirit of grace,
and even turning the grace of God into a license for the flesh.
These aren`'t hypothetical possibilities;
they are common temptations and real dangers for all of our hearts.
Because if we do not continually bring our will under the grace of God,
we will inadvertently keep grace under our feet.

Now this phrase "`under grace`" is one that Paul uses in Romans,
and it is often misunderstood.
In Romans 6:14, Paul says:

_For sin shall not have dominion over you, for you are not under law but under grace.
What then?
Shall we sin because we are not under law but under grace?
Certainly not!_

To understand what Paul means by being _under_ grace,
it is helpful first to ask in what sense Israel was _under_ the law.
I believe it is fair to say that Israel was under the law in _every conceivable_ sense.
The law of Moses ruled over them, it taught them,
it governed every aspect of their personal, religious, and civil lives.
It determined how they lived, how they related to one another, how they worshiped,
prepared food, raised children, dealt with sin and evil, cleaned their bodies and homes,
responded to disease, hired servants, etc.
There was no part of their life that was not brought _under_ its jurisdiction,
and submitted to its authority.
Yet, despite all of this, sin still had dominion in their inward man,
because (as we have seen) there is a great difference between a written word of law,
and an implanted Word of grace.

But Paul says, "`sin shall not have dominion over you,
for you are not under law _but under grace_.`"
Being under grace does not mean disregarding or dispensing with the law,
as some mistakenly believe.
Being under grace means continually bringing our hearts, our lives, our thoughts,
desires, and deeds, _under_ the rule of God`'s light and Spirit,
so that just as the law once governed the outward man,
now the Word of grace governs the heart, and through it the outward man as well.

Let us read a little more of this passage in Romans
to better understand the context of this statement.
He writes:

For sin shall not be master over you, for you are not under law but under grace.
What then?
Shall we sin because we are not under law but under grace?
May it never be!
Do you not know that when you present yourselves to someone as slaves for obedience,
you are slaves of the one whom you obey, either of sin resulting in death,
or of obedience resulting in righteousness? But thanks
be to God that though you were slaves of sin,
you became obedient from the heart to that form of teaching to
which you were delivered, and having been freed from sin,
you became slaves of righteousness.^
footnote:[Romans 6:14-18]

In other words: "`You are no longer obliged to be slaves of sin,
because you are no longer under the rule of an outward command,
but under the rule of an inward power.
Does this mean that you are free to sin because you
are not under the authority of the outward letter?
May it never be!
Do you not realize that when you give yourselves as slaves for obedience,
you are slaves to the one whom you obey?
You used to be inward slaves of sin, and outwardly controlled and condemned by the law.
But thanks be to God that, though you were slaves of sin,
you have become obedient from the heart to a new form of
teaching--__to the teaching of grace__--to which you were delivered.
And now,
having been made free from the power of sin by coming
under the even greater power of grace,
you have become slaves of righteousness.`"

Therefore, since grace has come,
since a measure of His fullness has been sown into our hearts,
and since our only hope of salvation lies in it,
and not in works of the flesh or works of the law,
"`let us go boldly to the throne of grace`"^
footnote:[Hebrews 4:16]
to abound more and more in this good and perfect gift.
And let us take seriously the following advice of Peter:

Therefore gird up the loins of your mind, be sober,
and rest your hope fully upon the grace that is to
be brought to you at the revelation of Jesus Christ;
as obedient children, not conforming yourselves to the former lusts,
as in your ignorance; but as He who called you is holy,
you also be holy in all your conduct, because it is written, "`BE HOLY, FOR I AM HOLY.`"^
footnote:[1 Peter 1:13-16]
